### ISSUE TITLE
No attention

### ISSUE THREAD

**Issue by caillonantoine** [lucidrains/denoising-diffusion-pytorch#1]
It seems that even if you implemented a LinearAttention module, you are not actually using it since every time you instantiate it, you use

```python
Residual(Rezero(LinearAttention(mid_dim)))
```
where the Rezero module discards its input parameter, resulting in an identity operation.

**Comment by lucidrains** [comment]
@caillonantoine Oh wow, thank you for catching this! https://github.com/lucidrains/denoising-diffusion-pytorch/releases/tag/0.3.2
