### ISSUE TITLE
Adding more tricks

### ISSUE THREAD

**Issue by JinshuChen** [lucidrains/denoising-diffusion-pytorch#105]
Hi Lucidrains,
Many thanks to your repo!
https://arxiv.org/pdf/2209.05442.pdf This paper seems to offer a few novel and valid tricks but I met some troubles when reproducing. Would you be interested in reproducing and adding those methods to your repository? : )

**Comment by pengzhangzhi** [comment]
It is weird that they don't open source the code

**Comment by lucidrains** [comment]
yea, i went through that paper but nothing really stuck out

which trick did you find most compelling?

**Comment by lucidrains** [comment]
ohh nevermind, they are two different things. i'm not really convinced about anything in this paper
