### ISSUE TITLE
RuntimeError: Trying to backward through the graph a second time 

### ISSUE THREAD

**Issue by prophet-Fang** [lucidrains/denoising-diffusion-pytorch#109]
Hi lucidrains,

I'm trying to run the exmple script (**Trainer** class) but  I'm getting this error:

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

I have tried to run the script line by line. Everything went well when I run **loss.backward()** for the first time, but the above problem occurred on the second run.

Thanks!

**Comment by lucidrains** [comment]
@prophet-Fang could you share the full script you are running?

**Comment by prophet-Fang** [comment]
Thanks for your reply! 
I have already found the reason: I use a _conv1D()_ to convert my data to the shape of the network's input, which is out of the training loop.

**Comment by lucidrains** [comment]
oh ok! great! closing
