### ISSUE TITLE
Unet's "Groups" is unused

### ISSUE THREAD

**Issue by torridgristle** [lucidrains/denoising-diffusion-pytorch#11]
It seems that "groups" for the Unet aren't used. It's not passed to the ResNetBlock modules nor the Block in the final_conv.

**Comment by lucidrains** [comment]
@torridgristle ohh yea, that's for the groupnorms - but i think i will be replacing the resnet blocks with the new convnext ones and aim for all layernorms

**Comment by lucidrains** [comment]
ok done! no more groups and groupnorms!

**Comment by drawcodeboy** [comment]
Was RMS Normalization used instead of Group Normalization because it was simpler to implement?

**Comment by lucidrains** [comment]
@drawcodeboy no, it was because Tero Karras (a renowned researcher in the space) showed that it hurts unets in his EDM2 paper

**Comment by drawcodeboy** [comment]
Thank you for your quick response! Your repository has been a great help in my studies, and I hope to become a contributor to your repository someday!

**Comment by lucidrains** [comment]
@drawcodeboy hehe no problem, go make the next big discovery with them
