### ISSUE TITLE
ddpm is disabled?

### ISSUE THREAD

**Issue by pengzhangzhi** [lucidrains/denoising-diffusion-pytorch#110]
Hi, I find this code disables the instantialization of `GaussianDiffusion` since it does not allow `self` to be `GaussianDiffusion`.
Why? Is this just a base class that can not be directly used?
https://github.com/lucidrains/denoising-diffusion-pytorch/blob/23fd887a5fcd48468bb79c744acb1e8bb8b0dc3b/denoising_diffusion_pytorch/denoising_diffusion_pytorch.py#L431

**Comment by lucidrains** [comment]
the logic reads: the base class cannot be used if the unet does not produce an output that is equal to the number of input channels

**Comment by pengzhangzhi** [comment]
> the logic reads: the base class cannot be used if the unet does not produce an output that is equal to the number of input channels

Thank you sooo much~
