### ISSUE TITLE
How can I use this source code?

### ISSUE THREAD

**Issue by dicaleon** [lucidrains/denoising-diffusion-pytorch#111]
I am confused about this source code.
Please help me...
In my opinion, this code is used to generate new images from training images just like GAN.
But how can we know the code works well or not?
・If [sample-xx.png] in folder [results] generated from training is clear and similar to training image, that means the training is successful. Is that right?
・However, if the [sample-xx.png] is very similar or same with training images, why we need this source code?
・I think the new images should be different with training images.
And how can I use checkpoint?
Valid image for the checkpoint should be a random noise image?

**Comment by lucidrains** [comment]
@dicaleon my repositories are mostly for doctorate students as well as professional in industry

would recommend https://huggingface.co/docs/diffusers/index , which should be much more friendly towards beginners

**Comment by lucidrains** [comment]
@dicaleon my repositories are mostly aimed at doctorate students as well as professionals in industry

would recommend https://huggingface.co/docs/diffusers/index , which should be much more friendly towards beginners
