### ISSUE TITLE
Learned sinusoidal position embeddings vs. random

### ISSUE THREAD

**Issue by tmabraham** [lucidrains/denoising-diffusion-pytorch#112]
Hey Phil,

I was curious about this line of code:
https://github.com/lucidrains/denoising-diffusion-pytorch/blob/aadaa7d288b08c442241f4fd961dcbfd4ad1d152/denoising_diffusion_pytorch/denoising_diffusion_pytorch.py#L151

this is by default `requires_grad=True` so it's a learnable parameter but I think in Kat's code it's not learnable. Or at least in Kat's k-diffusion codebase it is not learnable. Apparently I have heard from Kat these are random Fourier features, which I found out were first implemented for diffusion models in the score SDE Song et al. paper since they're better for continuous timesteps. 

Having it learned is supposedly fine too, but maybe you could add support for random Fourier features as well?

**Comment by lucidrains** [comment]
@tmabraham Thank you Tanishq! I had no idea they were fixed random fourier features

I've added the option https://github.com/lucidrains/denoising-diffusion-pytorch/blob/main/denoising_diffusion_pytorch/denoising_diffusion_pytorch.py#L274

**Comment by tmabraham** [comment]
Awesome! Thanks for adding this option!
