### ISSUE TITLE
Generation of a high-dimensional vector

### ISSUE THREAD

**Issue by yifei-liu-stat** [lucidrains/denoising-diffusion-pytorch#116]
Hi,

Thanks for this wonderful library! Can this library accommodate the DDPM to take a vector input (instead of images), for example, for high-dimensional vector generation? If it can, could you please point out how to do that? Thank you!

**Comment by lucidrains** [comment]
@yifei-liu-stat yeah definitely, that is the whole premise of latent diffusion. works best with the predict x0 objective

something like

```python
import torch
from denoising_diffusion_pytorch import Unet, GaussianDiffusion

model = Unet(
    dim = 64,
    dim_mults = (1, 2, 4),
    channels = 128
)

diffusion = GaussianDiffusion(
    model,
    image_size = 64,
    objective = 'pred_x0',
    timesteps = 1000
)

features = torch.randn(8, 128, 64, 64)

loss = diffusion(features)
loss.backward()

# after a lot of training

sampled_features = diffusion.sample(batch_size = 4)
sampled_features.shape # (4, 128, 64, 64)
```

**Comment by yifei-liu-stat** [comment]
Sorry, I am a little bit confused about the shape (for example, my input is a long 1d vector, so what does `image_size` specify in `GaussianDiffusion()`).

So if I have a training set with sample size `n` and dimension `p >> n`, should I first cast or reshape the long vector of dimension `p`  to a 2d or 3d tensor, then use the framework here? 

Also, is there some kind of documentation for this wonderful library, for example, where I can know the difference between using `pred_noise` and `pred_x0`?

Thank you!

**Comment by lucidrains** [comment]
@yifei-liu-stat i recommend reading the [original ddpm paper](https://arxiv.org/abs/2006.11239) to understand the objectives

being able to accommodate 1d signals is something i plan on supporting; i receive quite a number of emails asking for that

**Comment by yifei-liu-stat** [comment]
Sounds good, thank you!

**Comment by lucidrains** [comment]
@yifei-liu-stat let me know if https://github.com/lucidrains/denoising-diffusion-pytorch#miscellaenous helps
