### ISSUE TITLE
ConvNext appears to look worse, concerned

### ISSUE THREAD

**Issue by torridgristle** [lucidrains/denoising-diffusion-pytorch#13]
I'm training a model on illustrations with the new ConvNext modules and it's not giving me the results I expected from training with the same parameters and data before the ConvNext change. Previously it used to create lines and shapes of solid color, but now there aren't any smooth lines that appear when checking the output, it's like fuzzy scribbles instead.

Previous version without ConvNext: https://i.imgur.com/qeF0dNn.png
Current version with ConvNext: https://i.imgur.com/S3ierK5.png

These outputs are typical for the old and new code when I trained different models with differing parameters. Without ConvNext I get lines and shapes, with ConvNext I get lots of fuzzy but hard lines/edges.

It seems like maybe it's very slowly becoming less fuzzy over time but considering the amount of time that has to be put into training this I want to be sure that it's definitely going to work and that it has produced results with these changes.

**Comment by lucidrains** [comment]
@torridgristle hmm, maybe i jumped the gun a bit

do you want to try https://github.com/lucidrains/denoising-diffusion-pytorch/commit/eb6e1b508e920efd840f2fa13e80d60ce19ed2c1 and see if this helps? if you still don't get great results, i could rollback. i'm also doing a run on oxford102 dataset to see for myself

**Comment by lucidrains** [comment]
![sample-9](https://user-images.githubusercontent.com/108653/151916005-1199935c-c05f-44b3-864d-5fae68e0407a.png)
looking decent at 9k iterations, will let it run overnight

**Comment by lucidrains** [comment]
![sample-41](https://user-images.githubusercontent.com/108653/151989904-7449d76b-7098-428d-aee3-8da35c653768.png)

it is starting to look ok for me at 41k

**Comment by lucidrains** [comment]
![sample-44](https://user-images.githubusercontent.com/108653/152000532-b6032034-03c7-49c2-9230-06d67e60e073.png)

**Comment by lucidrains** [comment]
![sample-49](https://user-images.githubusercontent.com/108653/152014860-b401645e-b4c9-4a0c-bd97-db56fda782d4.png)

yea looks fine, at least for the oxford102 flowers
