### ISSUE TITLE
trainer.load() fails when using `accelerate launch`

### ISSUE THREAD

**Issue by lhaippp** [lucidrains/denoising-diffusion-pytorch#138]
Hi, thanks for your great job!

When I reload the checkpoints to continue training
```
trainer.load("200")
```
and execute `accelerate launch demo.py` with Multi GPUs (in my case, 4 GPUs), I met the problem:
```
AttributeError: 'Trainer' object has no attribute 'results_folder'
```

I suppose only the master(rank=0 GPU) needs to reload the checkpoints instead of every GPU session?
As a result, I changed the code a little bit (is it okay?):
```
def load(self, milestone):
    accelerator = self.accelerator
    device = accelerator.device

    if not self.accelerator.is_main_process:
        return
..........
```

**Comment by lucidrains** [comment]
@lhaippp Hi Li! Try `0.1.5` and see if that fixes your issue

**Comment by lhaippp** [comment]
Hi Phil, I check the `0.1.5` changes, however, I suppose that there could still happen another `ema loading issue`.

On the contrary, I think the code above has addressed my issue:
```
    if not self.accelerator.is_main_process:
        return
```

**Comment by lucidrains** [comment]
@lhaippp nice! could you possibly explain how to reproduce the ema error?

**Comment by lhaippp** [comment]
@lucidrains yes it indeed happens the `ema error`,  it seems strange, however, I guess the error is that only the master node (GPU:0) reloads the ema. 

the error log is as below:
```
Traceback (most recent call last):                                                                                                                                                                                                                                                        
  File "demo.py", line 33, in <module>                                                                                                                                                                                                                                                    
    trainer.load("200")                                                                                                                                                                                                                                                                   
  File "/data/denoising-diffusion-pytorch/work/20221219.ddpm.deepHomo/denoising_diffusion_pytorch/denoising_diffusion_pytorch.py", line 1052, in load                                                                                                                                     
    self.ema.load_state_dict(data['ema'])                                                                                                                                                                                                                                                 
AttributeError: 'Trainer' object has no attribute 'ema'                                                                                                                                                                                                                                   
Traceback (most recent call last):                                                                                                                                                                                                                                                        
  File "demo.py", line 33, in <module>                                                                                                                                                                                                                                                    
    trainer.load("200")                                                                                                                                                                                                                                                                   
  File "/data/denoising-diffusion-pytorch/work/20221219.ddpm.deepHomo/denoising_diffusion_pytorch/denoising_diffusion_pytorch.py", line 1052, in load                                                                                                                                     
    self.ema.load_state_dict(data['ema'])                                                                                                                                                                                                                                                 
AttributeError: 'Trainer' object has no attribute 'ema'                                                                                                                                                                                                                                   
Traceback (most recent call last):                                                                                                                                                                                                                                                        
  File "demo.py", line 33, in <module>                                                                                                                                                                                                                                                    
    trainer.load("200")                                                                                                                                                                                                                                                                   
  File "/data/denoising-diffusion-pytorch/work/20221219.ddpm.deepHomo/denoising_diffusion_pytorch/denoising_diffusion_pytorch.py", line 1052, in load
    self.ema.load_state_dict(data['ema'])
AttributeError: 'Trainer' object has no attribute 'ema'
```

**Comment by lhaippp** [comment]
@lucidrains Hi Phil, I have encountered extra problems related to `accelerate`, as I am really new to `accelerate`, would you mind helping me out? 

My core question is how to use a larger batch size.

1. the GPU memory of the master GPU is significantly higher than other GPUs, making it hard to increase the batch size. (However, in my mind, the naive PyTorch DDP could achieve a balance GPU memory distribution?)

![image](https://user-images.githubusercontent.com/22257640/210134265-ac642eef-9930-4528-be61-4883c1c68cff.png)


3. during `accelerate config`, if I set to use deepSpeed, after `accelerate launch demo.py`, it returns an error `AssertionError: You need to pass the model along the optimizer when using Deepspeed.`, the detail log is as below: 

```
Traceback (most recent call last):                                                                                                                                                                                 
  File "demo.py", line 33, in <module>                                                                                                                                                                             
    augment_horizontal_flip=False)                                                                                                                                                                                 
  File "/data/denoising-diffusion-pytorch/work/20221230.cond.rgbHomoFlow.9i6o/denoising_diffusion_pytorch/denoising_diffusion_pytorch.py", line 1474, in __init__                                                  
    dl = self.accelerator.prepare(dl)                                                                                                                                                                              
  File "/data/denoising-diffusion-pytorch/ddpm-pyTorch/lib/python3.6/site-packages/accelerate/accelerator.py", line 440, in prepare                                                                                
    result = self._prepare_deepspeed(*args)
  File "/data/denoising-diffusion-pytorch/ddpm-pyTorch/lib/python3.6/site-packages/accelerate/accelerator.py", line 577, in _prepare_deepspeed
    ), "You need to pass the model along the optimizer when using Deepspeed."
AssertionError: You need to pass the model along the optimizer when using Deepspeed.
    dl = self.accelerator.prepare(dl)
  File "/data/denoising-diffusion-pytorch/ddpm-pyTorch/lib/python3.6/site-packages/accelerate/accelerator.py", line 440, in prepare
    result = self._prepare_deepspeed(*args)
  File "/data/denoising-diffusion-pytorch/ddpm-pyTorch/lib/python3.6/site-packages/accelerate/accelerator.py", line 577, in _prepare_deepspeed
    ), "You need to pass the model along the optimizer when using Deepspeed."
AssertionError: You need to pass the model along the optimizer when using Deepspeed.
```

Following the accelerate tutorials, I rewrite the code to `self.model, self.opt, dl = self.accelerator.prepare(self.model, self.opt, dl)`, seems solving the problem.

4. After enabling deepSpeed as the configuration:
```
In which compute environment are you running? ([0] This machine, [1] AWS (Amazon SageMaker)): 0
Which type of machine are you using? ([0] No distributed training, [1] multi-CPU, [2] multi-GPU, [3] TPU): 2
How many different machines will you use (use more than 1 for multi-node training)? [1]: 1
Do you want to use DeepSpeed? [yes/NO]: yes
What should be your DeepSpeed's ZeRO optimization stage (0, 1, 2, 3)? [2]:
Where to offload optimizer states? [NONE/cpu/nvme]: NONE
How many gradient accumulation steps you're passing in your script? [1]: 2
How many GPU(s) should be used for distributed training? [1]:4
Do you wish to use FP16 or BF16 (mixed precision)? [NO/fp16/bf16]: NO
```

using the same batch size (32 in my case) causes the output of GPU memory error, in my mind, enabling deepspeed or fully data parallel should allow using a larger batch size？

**Comment by Mat-Po** [comment]
> @lucidrains yes it indeed happens the `ema error`, it seems strange, however, I guess the error is that only the master node (GPU:0) reloads the ema.
> 
> the error log is as below:
> 
> ```
> Traceback (most recent call last):                                                                                                                                                                                                                                                        
>   File "demo.py", line 33, in <module>                                                                                                                                                                                                                                                    
>     trainer.load("200")                                                                                                                                                                                                                                                                   
>   File "/data/denoising-diffusion-pytorch/work/20221219.ddpm.deepHomo/denoising_diffusion_pytorch/denoising_diffusion_pytorch.py", line 1052, in load                                                                                                                                     
>     self.ema.load_state_dict(data['ema'])                                                                                                                                                                                                                                                 
> AttributeError: 'Trainer' object has no attribute 'ema'                                                                                                                                                                                                                                   
> Traceback (most recent call last):                                                                                                                                                                                                                                                        
>   File "demo.py", line 33, in <module>                                                                                                                                                                                                                                                    
>     trainer.load("200")                                                                                                                                                                                                                                                                   
>   File "/data/denoising-diffusion-pytorch/work/20221219.ddpm.deepHomo/denoising_diffusion_pytorch/denoising_diffusion_pytorch.py", line 1052, in load                                                                                                                                     
>     self.ema.load_state_dict(data['ema'])                                                                                                                                                                                                                                                 
> AttributeError: 'Trainer' object has no attribute 'ema'                                                                                                                                                                                                                                   
> Traceback (most recent call last):                                                                                                                                                                                                                                                        
>   File "demo.py", line 33, in <module>                                                                                                                                                                                                                                                    
>     trainer.load("200")                                                                                                                                                                                                                                                                   
>   File "/data/denoising-diffusion-pytorch/work/20221219.ddpm.deepHomo/denoising_diffusion_pytorch/denoising_diffusion_pytorch.py", line 1052, in load
>     self.ema.load_state_dict(data['ema'])
> AttributeError: 'Trainer' object has no attribute 'ema'
> ```

@lhaippp Hi, I am facing the same problem here when i am trying to resume my training. Did you menage to solve it maybe?

**Comment by Hayoung93** [comment]
For someone's information, I changed `if calculate_fid:` to `if calculate_fid and self.accelerator.is_main_process` to solve `ema` error (line no. `916` of `denoising_diffusion_pytorch.py`).
