### ISSUE TITLE
1D Sampling Generates Only Positive Values

### ISSUE THREAD

**Issue by TitanKaz** [lucidrains/denoising-diffusion-pytorch#142]
When trying to sample from trained 1D model it can predicts/sample only positive values.
Probably cause the "normalize_to_zero_to_one" function used in the "p_sample_loop".
Better add feature to choose if to enable or not - when training/sampling audio data it wont work

**Comment by lucidrains** [comment]
@TitanKaz ohh, try setting https://github.com/lucidrains/denoising-diffusion-pytorch/commit/a772416afa6940f5e306a8cc2ebbb7c9e2a8dd43#diff-8e1d7926b1192bbf109333c6f8c69b62c7379a0e7734be774344cbb2c4f0e54bR418 to `False` in version 1.0.1
