### ISSUE TITLE
How to modify this to handle non-image data

### ISSUE THREAD

**Issue by sgbaird** [lucidrains/denoising-diffusion-pytorch#15]
Curious if you have any thoughts of how this can be applied to something other than image data. In my case, it's a task in materials informatics.

**Comment by mrkatey** [comment]
Have you considered transforming your data examples into a series of images? Sorry if that sounds too simple.

**Comment by sgbaird** [comment]
@mrkatey I've noticed that most of lucidrains's repos allow for passing tensors directly, which is great. I think it still assumes n-channel square images in many cases (not sure if `image_size` could take a tuple of shapes), which makes a lot of sense. I've been doing something along the lines of what you mentioned in a package called [`xtal2png`](https://xtal2png.readthedocs.io/en/latest/) (crystal to PNG). Still testing the performance of the representation.
