### ISSUE TITLE
The difference between pred_x0, pred_v, pred_noise three objectives

### ISSUE THREAD

**Issue by lzl2040** [lucidrains/denoising-diffusion-pytorch#153]

**Comment by lucidrains** [comment]
you'll need to read the following papers

https://arxiv.org/abs/2006.11239 (predict start, predict noise)
https://arxiv.org/abs/2202.00512 (predict v)

**Comment by Birch-san** [comment]
https://learnopencv.com/denoising-diffusion-probabilistic-models/#Training-Objective-&-Loss-Function-Used-In-Denoising-Diffusion-Probabilistic-Models

<img width="776" alt="image" src="https://github.com/lucidrains/denoising-diffusion-pytorch/assets/6141784/26779a93-2f73-4730-8f72-8c96392858d3">
