### ISSUE TITLE
Support for Incorporate Embedding Layer before Denoise 

### ISSUE THREAD

**Issue by Leo-T-Zang** [lucidrains/denoising-diffusion-pytorch#157]
Hi Phil @lucidrains ,

I found some recent NLP and Diffusion work. They first embed 1d input (tokens) into a 2d matrix and then make the diffusion and denoise. I tried to incorporate such feature within your framework but failed several times. Do you have any suggestions or ideas about how to implement it?

Thank you so much :)

Attach Links of two papers here.
[Diffusion LM](https://github.com/XiangLi1999/Diffusion-LM)
[Diffusion Seq2Seq](https://github.com/Shark-NLP/DiffuSeq)

**Comment by lucidrains** [comment]
@Leo-T-Zang hey Leo, both of your links go to fully open sourced code repositories

unless they are not functional, why wouldn't you work off their repositories?
