### ISSUE TITLE
classifier guided diffusion

### ISSUE THREAD

**Issue by pengzhangzhi** [lucidrains/denoising-diffusion-pytorch#158]
Are you interested in adding a feature where the model can sample when a class label is given?
openai-guided-diffusion implements this feature in 
https://github.com/openai/guided-diffusion/blob/8fb3ad9197f16bbc40620447b2742e13458d2831/guided_diffusion/gaussian_diffusion.py#L395

**Comment by lucidrains** [comment]
@pengzhangzhi is this what you are looking for? https://github.com/lucidrains/denoising-diffusion-pytorch/blob/main/denoising_diffusion_pytorch/classifier_free_guidance.py

**Comment by pengzhangzhi** [comment]
Classifier-free guidance is a good strategy! But I am looking for classifier guided. The idea that uses an external guidance function to control the generation trajectory is powerful. I am trying to extend this idea to other filed. If you are interested, I am happy to submit a pr for this feature : )

**Comment by ptoyip** [comment]
@pengzhangzhi Thanks for your contribution!
I'm modifying the code to try to implement the guided_diffusion on 1D data, I'm not sure how to train the diffusion process. 
Lets suppose we have normal pictures (256x256x3), what I need to do to train using the `guided_diffusion.py`? Or I just simply train the classifier following the step from https://github.com/openai/guided-diffusion/blob/main/scripts/classifier_train.py and train the diffusion model without guidance like normal and only combine these two during sampling?
