### ISSUE TITLE
Interpolations

### ISSUE THREAD

**Issue by robbieg729** [lucidrains/denoising-diffusion-pytorch#159]
I'm confused about the interpolation method, since in the p_sample function call the 't' parameter is not an int even tho it is specified that it must be in the p_sample function definition. If I replace this with 'i', I just get a new batch of 64 images rather than interpolants. What am I doing wrong?

**Comment by lucidrains** [comment]
@robbieg729 oops, i've neglected the interpolate functions for some time

should be corrected in the latest version!
