### ISSUE TITLE
Implementing the new and shinny U-ViT arch

### ISSUE THREAD

**Issue by tcapelle** [lucidrains/denoising-diffusion-pytorch#163]
I am reading this recently released paper and this architecture that does not need a VAE to produce high-resolution images without the need for latent diffusion looks very promising. The arch is pretty simple, but no implementation yet appears to be available:
https://arxiv.org/pdf/2301.11093.pdf
Could you let me know if you are planning on adding this? Would this repo be the place? Are you open to help in doing so?
Sincerely yours,
Thomas

**Comment by lucidrains** [comment]
@tcapelle hello Thomas

yup, will be building it out [here](https://github.com/lucidrains/denoising-diffusion-pytorch/pull/161)

**Comment by tcapelle** [comment]
I think that the simplest `to_patch` model should do fine anyway, as they say on the paper.

**Comment by lucidrains** [comment]
![Screenshot from 2023-01-30 10-25-57](https://user-images.githubusercontent.com/108653/215563331-55c89423-fe9d-4ba0-883d-a1e500ad1b95.png)

**Comment by lucidrains** [comment]
@tcapelle you want to give what is over at https://github.com/lucidrains/denoising-diffusion-pytorch/pull/161 a try? i added the patched method, but dwt will probably take some further work, as the repositories i'm looking at do not seem mature, and i may just work it out myself and include the functions directly in the file

**Comment by lucidrains** [comment]
nevermind, this looks pretty good https://pywavelets.readthedocs.io/en/latest/install.html will probably incorporate this

**Comment by tcapelle** [comment]
Wow that was fast (as always) but I am on holidays in the south of Chile. I will take a look as soon as I come back.

**Comment by lucidrains** [comment]
@tcapelle have fun down there!

**Comment by lucidrains** [comment]
seems to be working, released without dwt (can be added manually by passing in [two modules](https://github.com/lucidrains/denoising-diffusion-pytorch/blob/main/denoising_diffusion_pytorch/simple_diffusion.py#L318-L319))

**Comment by tcapelle** [comment]
I will!
