### ISSUE TITLE
[feature request] Evaluation Metric During Training (FID, IS, KID, etc..)

### ISSUE THREAD

**Issue by lhaippp** [lucidrains/denoising-diffusion-pytorch#164]
Hi Phil,

Thanks again for the great job! 

I did some experiments with image motion (such as optical flow) based on this repo, and the qualitative results look good. Thus I am wondering if the calculation of validation metrics (such as FID score) could be added to the training process, so that there would be a series of quantitative results to refer to?

**Comment by lucidrains** [comment]
@lhaippp yea sure! happy to accept PRs

maybe integrating something like https://github.com/mseitzer/pytorch-fid for starters?

**Comment by lhaippp** [comment]
@lucidrains Referring to (k-diffusion)[https://github.com/crowsonkb/k-diffusion] and (pytorch-fid)[https://github.com/mseitzer/pytorch-fid], I separatively implemented the evaluation metrics.

However, based on the same dataset, I got inconsistent results (178(k-diffusion) vs 146(pytorch-fid)). So maybe I still need some time to debug..
