### ISSUE TITLE
Question about the confusing logic about `return_all_timesteps` param in `GaussianDiffusion.ddim_sample()`

### ISSUE THREAD

**Issue by Li-Qingyun** [lucidrains/denoising-diffusion-pytorch#166]
The logic of `GaussianDiffusion.ddim_sample()` is confusing when `return_all_timesteps=True`.
It seems that, the first `img` (random noise) is appended twice. However, the last `img` (x_start, the output generated image) is not appended. The position of the list appending and the continue is confusing for me.
This issue is created to discuss the problem.
I also create PR #165 to show and commit my opinion about the implementation.

**Comment by lucidrains** [comment]
@Li-Qingyun Oh yes, thank you for catching this! could you let me know if [this commit](https://github.com/lucidrains/denoising-diffusion-pytorch/commit/f4b6a08405c2f02302ce23596b70248601bed41c) fixes it in 1.1.1?

**Comment by Li-Qingyun** [comment]
It seems fixed.

**Comment by Li-Qingyun** [comment]
But why the `continue` must be kept?
