### ISSUE TITLE
Images not being saved in results folder during model training

### ISSUE THREAD

**Issue by yyswhsccc** [lucidrains/denoising-diffusion-pytorch#168]
Hello!

I would like to thank the developers for creating such an amazing image generation model. However, I am currently facing an issue where the generated images are not being saved in the results folder during model training.

I am running the model on a Windows machine and have ensured that the results folder exists and has the necessary permissions. Despite this, the results folder remains empty even after the model training has completed successfully. 

I would really appreciate any help in resolving this issue.

**Comment by yyswhsccc** [comment]
solved. nvm and thanks!

**Comment by mingxingpu** [comment]
> solved. nvm and thanks!

I also facing this issue, could you help me? pls

**Comment by yyswhsccc** [comment]
I am sorry that’s long time ago, I already forgot how to solve it 🥲 I
think you could post this issue again?

Sorry for that!

mxpp99 ***@***.***>于2024年6月13日 周四下午3:22写道：
