### ISSUE TITLE
the sample results are training images

### ISSUE THREAD

**Issue by JunMa11** [lucidrains/denoising-diffusion-pytorch#17]
Dear @lucidrains ,

Thanks for the great repo.

I was wondering whether the model is generating training set images?

Here is a saved sample during training. The results look very good but I found all the images are training images.

![sample-179](https://user-images.githubusercontent.com/19947331/158485944-8a62ea16-3f37-4f10-9221-0095ad4178dd.png)

**Comment by lucidrains** [comment]
![Screenshot from 2022-03-16 10-56-59](https://user-images.githubusercontent.com/108653/158656314-2368e6d0-eb35-443a-b7bd-0bb7e7c9b5f6.png)

even this one?

**Comment by lucidrains** [comment]
how big is your training set?

**Comment by JunMa11** [comment]
Hi @lucidrains 

Thanks for your reply very much.

I'm using this horse dataset 
https://drive.google.com/file/d/1BdF0P60rlM5YXfaSFq3HlnMYGVqtnqvh/view?usp=sharing

It has 140 images. The following image in the training set is very similar to what you point out. Most of the remaining images can find very similar images in the training set.

![n02391049_9740](https://user-images.githubusercontent.com/19947331/158717884-bcf4da3e-4c22-4733-9212-f5717eee49ee.jpg)

**Comment by lucidrains** [comment]
@JunMa11 yea, so 140 images is nothing when it comes to ML / AI - you need at least 10k images or more, and even that is considered not enough (typically companies would train on millions of images)

**Comment by lucidrains** [comment]
<img width="134" alt="Screen Shot 2022-03-16 at 8 55 41 PM" src="https://user-images.githubusercontent.com/108653/158733959-f7cd8d40-fef9-4eda-8283-3d667a3ff22d.png">
😎

**Comment by askerlee** [comment]
Purely speculation: it may be the case that smaller datasets match smaller models (with reduced number of channels etc.), so that it forces the model to generalize, instead of remembering original imges.

**Comment by somepago** [comment]
Hi, I am trying to train the model on a small dataset. Your results look really good. Can you share the hyperparameters you used to train this? Thanks!
