### ISSUE TITLE
How to compute negative log-likelihood (nll) or bits per dimension (bpd)?

### ISSUE THREAD

**Issue by davitpapikyan** [lucidrains/denoising-diffusion-pytorch#172]
I wonder is there a way to estimate negative log-likelihood or bpd? 
For reference see Table 1 in [Improved Denoising Diffusion Probabilistic Models](https://arxiv.org/pdf/2102.09672.pdf).

**Comment by DevashishPrasad** [comment]
Were able to find a good way to compute negative log-likelihood or bpd?

Thank you!

**Comment by davitpapikyan** [comment]
Sure, check this [function](https://github.com/davitpapikyan/Normalizing-Flow-with-Diffusion-Prior-Model/blob/master/normalizing_flow/utils.py#L244).
