### ISSUE TITLE
model_mean calculation for VDM

### ISSUE THREAD

**Issue by jsun57** [lucidrains/denoising-diffusion-pytorch#173]
Hi, I am wondering if this model_mean calculation is correct, as the original paper says, the leading coefficient of mu_theta is alpha_s / alpha_t for t > s. And in the implementation, it seems the order is wrong.

https://github.com/lucidrains/denoising-diffusion-pytorch/blob/2f85f7a88003f038b19b4d703b4009dc4cd1bfe9/denoising_diffusion_pytorch/continuous_time_gaussian_diffusion.py#L207

**Comment by lucidrains** [comment]
![Screenshot from 2023-02-24 07-45-29](https://user-images.githubusercontent.com/108653/221222564-2f2fd407-be2c-45ec-ac57-f1076a9f9043.png)

so this expression is actually identical to what is two lines below, if you substitute `x_start`  with  `(x - sigma * pred_noise) / alpha`

do you see any issues with the following equation?

```python
model_mean = alpha_next / alpha * (x - c * sigma * pred_noise)
```

**Comment by jsun57** [comment]
Sorry for the confusion. My question is about the coefficient. It seems in the code alpha_next represent alpha_t, and alpha represent alpha_s. So the implementation says alpha_t/alpha_s. However, the paper says alpha_s/alpha_t.

**Comment by lucidrains** [comment]
@jsun57 ahh no, in the code, `alpha_next` should correspond to `s`

**Comment by jsun57** [comment]
@lucidrains I see. Thanks for the reply! I just want to make sure I understand the notations correctly. For the output of `learned_noise_schedule(time)`, does it refer to `gamma_eta(t)` in the paper or `-gamma_eta(t)`?

**Comment by lucidrains** [comment]
@jsun57 could you link to the specific parts of the code with `gamma_eta`?

**Comment by jsun57** [comment]
Sure. These are my confusions:
1. As you mentioned, `time_next` refers to `s` and `time` refers to `t`. Then, in paper, we have 
<img width="236" alt="Screenshot 2023-02-24 at 3 48 54 PM" src="https://user-images.githubusercontent.com/17034746/221299742-60c7213d-18f9-4618-81de-f71a8d809272.png">
with <img width="131" alt="Screenshot 2023-02-24 at 3 54 10 PM" src="https://user-images.githubusercontent.com/17034746/221300505-d139c21f-bf80-4506-bd37-e75b15aeabad.png">
as posterior variance. In your implementation you have: 

`squared_sigma_next = (-log_snr_next).sigmoid()`
and the signs are opposite. So I want to make sure that 
<img width="289" alt="Screenshot 2023-02-24 at 4 00 12 PM" src="https://user-images.githubusercontent.com/17034746/221301402-f0d94911-a435-468f-9020-633a4716e90a.png">
calculated from the 

`learned_noise_schedule ` are actually `-gamma_eta()`.

**Comment by lucidrains** [comment]
@jsun57 ah yes, sorry but i believe my noise functions output the negative of the gamma

<img width="629" alt="Screen Shot 2023-02-24 at 2 15 17 PM" src="https://user-images.githubusercontent.com/108653/221303762-f5891958-1815-46e5-8e80-f8598706329a.png">

https://github.com/lucidrains/denoising-diffusion-pytorch/blob/main/denoising_diffusion_pytorch/continuous_time_gaussian_diffusion.py#L67

**Comment by lucidrains** [comment]
to be honest, the learned noise function approach has never worked that well, nor is it adopted by any subsequent papers. you will get very far just by using the cosine schedule

**Comment by jsun57** [comment]
I see. Thanks a lot for you reply!

**Comment by lucidrains** [comment]
no problem, happy studying
