### ISSUE TITLE
Possible bug in alpha_bar

### ISSUE THREAD

**Issue by jihoonerd** [lucidrains/denoising-diffusion-pytorch#18]
Thanks for all the work you shared.

I noticed the recent update in ddpm code and found possible bug: 

https://github.com/lucidrains/denoising-diffusion-pytorch/blob/0b8cdb4c8bf96384ebf31a4fdc4fcb59a1242cb9/denoising_diffusion_pytorch/denoising_diffusion_pytorch.py#L321

The line was previously:

https://github.com/lucidrains/denoising-diffusion-pytorch/blob/f4615599bcbc884dcb7efa0dd70840f011a0fbb9/denoising_diffusion_pytorch/denoising_diffusion_pytorch.py#L337

From my understanding, padding should be applied to the left instead of right, which may require modification:

```python
alphas_cumprod_prev = F.pad(alphas_cumprod[:-1], (1, 0), value = 1.) 
```

to make them equivalent.

**Comment by lucidrains** [comment]
@jihoonerd oh yes :man_facepalming: thank you so much for catching this!
