### ISSUE TITLE
Why execute sample() on single GPU?

### ISSUE THREAD

**Issue by lhaippp** [lucidrains/denoising-diffusion-pytorch#180]
Hi Phil,

I'm a little confused about the sample() during training

[denoising-diffusion-pytorch/denoising_diffusion_pytorch/denoising_diffusion_pytorch.py line-980](https://github.com/lucidrains/denoising-diffusion-pytorch/blob/64061aff4006b80c20f34dc2f5508326750fc1b4/denoising_diffusion_pytorch/denoising_diffusion_pytorch.py#L980)

why not leverage all GPUs?

**Comment by lucidrains** [comment]
@lhaippp i only wanted the main process to keep track of the exponential moving averaged network, which is used to sample from

**Comment by lhaippp** [comment]
ok, I was not sure about it (sample with EMA).
