### ISSUE TITLE
Possible bug in cosine_beta_schedule

### ISSUE THREAD

**Issue by Zhengxinyang** [lucidrains/denoising-diffusion-pytorch#19]
Thanks for all the work you shared.

I found possible bug: the `cosine_beta_schedule` function should be
``` python
def cosine_beta_schedule(timesteps, s=0.008):
  steps = timesteps + 1
  x = torch.linspace(0, timesteps, steps)
  alphas_cumprod = torch.cos(((x / timesteps) + s) / (1 + s) * math.pi * 0.5) ** 2
  alphas_cumprod = alphas_cumprod / alphas_cumprod[0]
  betas = 1 - (alphas_cumprod[1:] / alphas_cumprod[:-1])
  
  return torch.clip(betas, 0, 0.999)
```

Now the function is:
``` python
def cosine_beta_schedule(timesteps, s = 0.008):
    steps = timesteps + 1
    x = torch.linspace(0, steps, steps)
    alphas_cumprod = torch.cos(((x / steps) + s) / (1 + s) * torch.pi * 0.5) ** 2
    alphas_cumprod = alphas_cumprod / alphas_cumprod[0]
    betas = 1 - (alphas_cumprod[1:] / alphas_cumprod[:-1])
    return torch.clip(betas, 0, 0.999)
```

**Comment by lucidrains** [comment]
@Zhengxinyang hmm, are you sure? so `torch.linspace(0, 3, 3)` would give `tensor([0.0000, 1.5000, 3.0000])`, but `torch.linspace(0, 2, 3)` would give `tensor([0.0, 1.0, 2.0])`

**Comment by Zhengxinyang** [comment]
@lucidrains Your understanding of `torch.linespace` is exactly correct, but in [Improved Denoising Diffusion Probabilistic Models](https://openreview.net/forum?id=-NEXDKk8gZ)  Eq. 18:

<img src="https://latex.codecogs.com/svg.image?\bar{\alpha}_{t}=\frac{f(t)}{f(0)},&space;\quad&space;f(t)=\cos&space;\left(\frac{t&space;/&space;T&plus;s}{1&plus;s}&space;\cdot&space;\frac{\pi}{2}\right)^{2},&space;s=0.008&space;" title="https://latex.codecogs.com/svg.image?\bar{\alpha}_{t}=\frac{f(t)}{f(0)}, \quad f(t)=\cos \left(\frac{t / T+s}{1+s} \cdot \frac{\pi}{2}\right)^{2}, s=0.008 " />
 the index t should be integer.

**Comment by lucidrains** [comment]
@Zhengxinyang :pray: yes, actually i looked at your correction and thought it was my code, when in fact i had the wrong code, and you were fixing mine! :man_facepalming:  thank you!
