### ISSUE TITLE
Outputs fixed in [-1,1] range

### ISSUE THREAD

**Issue by paulcjh** [lucidrains/denoising-diffusion-pytorch#20]
All of my outputs from the diffusion model, following the code snippets, are bounded between -1 to 1. Is this meant to be the case? I couldn't find anything obvious in this repo that would cause that.

My images are all square matching the same image size that's passed into the `GaussianDiffusion` model and pixel values are between 0-255. I saw that whenever I'm was trying to display the images as a result of `model.sample(...)` I was getting what seemed like noise on the output, and also noticed that during training my loss is stuck around 0.8 as shown below after 2.5k iterations (image size: 128, batch: 32, l1 loss, lr: 0.0001, time_steps: 4000 instead of the default 1000, also had similar with the default time steps):
<img width="1170" alt="Screenshot 2022-05-01 at 20 13 55" src="https://user-images.githubusercontent.com/47833405/166161021-cdece152-085a-4b8a-8902-3521545b8ab9.png">

**Comment by paulcjh** [comment]
Just seen the rescaling to [0,1] here: https://github.com/lucidrains/denoising-diffusion-pytorch/blob/e274fb305a8f37b0972a8475f282913a9a637f59/denoising_diffusion_pytorch/denoising_diffusion_pytorch.py#L583
Should image inputs also be rescaled to this range?

**Comment by paulcjh** [comment]
I see in the included Dataset that it is scaled:
`https://github.com/lucidrains/denoising-diffusion-pytorch/blob/e274fb305a8f37b0972a8475f282913a9a637f59/denoising_diffusion_pytorch/denoising_diffusion_pytorch.py#L475`

**Comment by lucidrains** [comment]
@paulcjh Hi Paul, yes, that is indeed the case. DDPM images need to be normalized from -1 to 1. It's been an area of frequent confusion, so I'm wondering if there's anyway I can programmatically warn researchers if the tensors being passed in isn't normalized properly

**Comment by paulcjh** [comment]
@lucidrains No worries, I should have searched a bit more thoroughly in the code! What I usually find super useful is a note on the readme describing the expected inputs+outputs per model (or the main ones) used

**Comment by beantr96** [comment]
@lucidrains Can I ask a very naive question why we need to normalize between -1 and 1?
