### ISSUE TITLE
Train simple diffusion

### ISSUE THREAD

**Issue by pribadihcr** [lucidrains/denoising-diffusion-pytorch#200]
Hi @lucidrains 

How to train simple diffusion model (Tim Salimans ) ?. Thanks

**Comment by lucidrains** [comment]
Thomas has a nice wandb report on using simple diffusion for forecasting https://wandb.ai/capecape/train_sd/reports/How-To-Train-a-Conditional-Diffusion-Model-From-Scratch--VmlldzoyNzIzNTQ1
