### ISSUE TITLE
Can I decrease the Time Step Number and Increase Noise?

### ISSUE THREAD

**Issue by Leo-T-Zang** [lucidrains/denoising-diffusion-pytorch#206]
Hi Phil and all,

I am wondering if I could increase the size of noise at each time step and decrease the total timestep from 1,000 to for example 400 steps in forward process?

If so, how should I adjust the parameters?

Thanks.

**Comment by lucidrains** [comment]
@Leo-T-Zang you can use ddim sampling, which is automatically used if you set [this hyperparameter](https://github.com/lucidrains/denoising-diffusion-pytorch/blob/main/denoising_diffusion_pytorch/denoising_diffusion_pytorch.py#L450) to be less than the `timesteps`

**Comment by lucidrains** [comment]
@Leo-T-Zang there's probably a lot of other better sampling methods out there by now. i haven't been keeping up with that body of research

**Comment by Leo-T-Zang** [comment]
@lucidrains Thanks for the reply. But I am not looking for smaller sampling steps. Instead, I am curious if I can decrease training steps from 1,000 to smaller with larger noise. Is this possible to do?
