### ISSUE TITLE
Regarding classifier free guidance implementation

### ISSUE THREAD

**Issue by ArmanMaesumi** [lucidrains/denoising-diffusion-pytorch#207]
In `classifier_free_guidance.py` we have this snippet:

```
    def forward_with_cond_scale(
        self,
        *args,
        cond_scale = 1.,
        **kwargs
    ):
        logits = self.forward(*args, cond_drop_prob = 0., **kwargs)

        if cond_scale == 1:
            return logits

        null_logits = self.forward(*args, cond_drop_prob = 1., **kwargs)
        return null_logits + (logits - null_logits) * cond_scale
```

In equation (6) of the [Classifier-Free Diffusion Guidance](https://arxiv.org/pdf/2207.12598.pdf) paper, the linear combination of the score estimates is `(1+w)*conditional - w*unconditional`.

Following the algebra:
`(1+w)*c - w*u = c + w*c - w*u = c + (c-u)*w`

But in the above code snippet it looks like we have `u + (c - u)*w`. Am I misunderstanding?

**Comment by lucidrains** [comment]
@ArmanMaesumi it is the same, i just have mine start at 1, while theirs start at 0

**Comment by ArmanMaesumi** [comment]
Ah yea, makes sense.
