### ISSUE TITLE
It exists a bug in FID calculation method

### ISSUE THREAD

**Issue by hxwork** [lucidrains/denoising-diffusion-pytorch#213]
Hi,

Many thanks for your code and it really helps a lot. When I calculate FID during training, the values are always between 0 and 1. I have checked the code and found that np.cov(matrix, rowvar=False) and torch.cov(matrix) have different results. So I found another code to compute the covariance using torch, and here is the code
```
def cov(tensor, rowvar=True, bias=False):
    """Estimate a covariance matrix (np.cov)"""
    tensor = tensor if rowvar else tensor.transpose(-1, -2)
    tensor = tensor - tensor.mean(dim=-1, keepdim=True)
    factor = 1 / (tensor.shape[-1] - int(not bool(bias)))
    return factor * tensor @ tensor.transpose(-1, -2).conj()
```
Hope this information is helpful.

Best,
Stephen

**Comment by lucidrains** [comment]
@hxwork oh yes, thank you for catching this

i think i made a mistake switching from numpy to torch [here](https://github.com/lucidrains/denoising-diffusion-pytorch/pull/178/files#diff-1ef0846017d5c27bd277b66e5afcab8798667afd39675e6f9382fc7e87a1fe28R920), and the `rowvar` just requires it to be transposed

do you want to see if 1.5.7 resolves this?

**Comment by hxwork** [comment]
Hi,

I have tested this, and it seems there is another error that may be caused by the computation precision. I paste the error here.
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/46584121/236725215-6fc026d1-8014-4874-b821-bca329412e63.png">
I am not sure if changing `atol` to a larger value is the best way to solve the problem.

**Comment by lucidrains** [comment]
this issue suggests it has to do with the size of the dataset https://github.com/mseitzer/pytorch-fid/issues/13

**Comment by hxwork** [comment]
Actually, I can run this code by switching from torch to numpy. I think this may be not related to the size of the dataset. This error is raised by `np.allclose()` since `0.003715... is a little bit larger than the value of `atol`.

**Comment by lucidrains** [comment]
weird, I did not hit that error when I did a trial run

does the error disappear if you simply use np.cov?

**Comment by hxwork** [comment]
I will give you the feedback after checking this later.

**Comment by hxwork** [comment]
Hi,

I have tested it. FYI, this error will disappear by just changing torch.cov to np.cov.

**Comment by lucidrains** [comment]
@hxwork i had been rerunning the experiments and it also breaks after a while (didn't run it for long enough the first time). changing it back to np.cov also fixed it for me, so let us just go with that! https://github.com/lucidrains/denoising-diffusion-pytorch/commit/fc6ff67d0371df8574e63b572a8b647800f3c639

**Comment by hxwork** [comment]
OK. No problem.

**Comment by dv-fenix** [comment]
Hi @lucidrains 
I faced a similar issue recently when using clean-fid for another project. Stumbled onto this issue while trying to find a fix.

In my case, this discussion wasn't really helpful. Upon further analysis, the error seems to stem from numerical errors in `scipy.linalg.sqrtm` for calculating the square roots of large sparse matrices (2048x2048 in my case). 

What worked for me was replacing that with the following:
`covmean = linalg.fractional_matrix_power(sigma1.dot(sigma2), 0.5)`

Hope this helps!
