### ISSUE TITLE
Self-Conditioning for Classifier Free Guidance

### ISSUE THREAD

**Issue by Leo-T-Zang** [lucidrains/denoising-diffusion-pytorch#217]
Hi Phil,

I notice in **classifier free guidance**, you **did not inlcude self-conditioning**.
Is that possible to use self-conditioning, or there is a specific reason not using it?
Thanks.

**Comment by lucidrains** [comment]
@Leo-T-Zang yeah, you can definitely include it, i just didn't do so for the classifier free guidance example

**Comment by Leo-T-Zang** [comment]
Thanks!

**Comment by qingninggo** [comment]
I wanted to ask, if there is no self-conditioning, does that not affect the effect?
