### ISSUE TITLE
How to train text-guided diffusion?

### ISSUE THREAD

**Issue by HerocatUED** [lucidrains/denoising-diffusion-pytorch#221]

**Comment by Adversarian** [comment]
I don't think this repository supports text-to-image. You would need to add a text encoder component that injects information from your prompt into your backward diffusion process and use a contrastive loss to measure the similarity of the generated images with the respective prompts. I can refer you to [this](https://openai.com/research/clip) and [this](https://arxiv.org/abs/2112.10741) but I believe [HuggingFace](https://huggingface.co/docs/diffusers/main/en/training/text2image) already provides a training facility for your desired task.

**Comment by HerocatUED** [comment]
I see, thank you!
