### ISSUE TITLE
Forward and backward diffusion for a set number of steps.

### ISSUE THREAD

**Issue by Adversarian** [lucidrains/denoising-diffusion-pytorch#223]
Hi, I hope your day is going well!
First I'd like to start by thanking on this phenomenal implementation.

I'm conducting some experiments that require that I first add noise to a given image for a fraction of the total num_steps and then perform backward diffusion for the same amount of time to get to the original image once again.

As I understand, there exist utility functions (namely `q_sample` and `p_sample`) that could potentially aid me in this task but I'm uncertain as to how I should proceed if I don't wish to start sampling from a pure isotropic Gaussian noise. Is there anyway what I described is achievable with the current implementation? 

Thanks in advance.

**Comment by ZHEGG** [comment]
Hello, I also want to add noise from the original image and then select a certain step size to denoise so as to achieve different image generation. just like the forward-backward process you said, do you have any reference？
