### ISSUE TITLE
EinopsError

### ISSUE THREAD

**Issue by brodymaddox** [lucidrains/denoising-diffusion-pytorch#232]
Hi, I'm running a basic model defined as below. 
(I added a simple pass-thru parameter for the loss function)

Every time I run trainer.train() I receive the EinopsError below the model definition.
Super confused here, I would really appreciate any help. Thank you!

model = Unet(
    dim = 64,
    dim_mults = (1,2,4,8),
    flash_attn = True)

diffusion = GaussianDiffusion(
    model,
    image_size=100,
    timesteps=1000,
    sampling_timesteps=250,
    loss_function=F.mse_loss)

trainer = Trainer(
    diffusion,
    path_to_original_mel_spectrograms,
    train_batch_size = train_batch_size,
    train_lr = train_lr,
    train_num_steps = train_num_steps,
    gradient_accumulate_every = 2,
    ema_decay = 0.995,
    amp=True,
    calculate_fid = False)

EinopsError                               Traceback (most recent call last)
Cell In[9], line 2
      1 #Train DDPM
----> 2 trainer.train()

File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\denoising_diffusion_pytorch\denoising_diffusion_pytorch.py:989, in Trainer.train(self)
    986 data = next(self.dl).to(device)
    988 with self.accelerator.autocast():
--> 989     loss = self.model(data)
    990     loss = loss / self.gradient_accumulate_every
    991     total_loss += loss.item()

File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py:1501, in Module._call_impl(self, *args, **kwargs)
   1496 # If we don't have any hooks, we want to skip the rest of the logic in
   1497 # this function, and just call forward.
   1498 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1499         or _global_backward_pre_hooks or _global_backward_hooks
   1500         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501     return forward_call(*args, **kwargs)
   1502 # Do not call functions when jit is used
   1503 full_backward_hooks, non_full_backward_hooks = [], []

File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\accelerate\utils\operations.py:553, in convert_outputs_to_fp32.<locals>.forward(*args, **kwargs)
    552 def forward(*args, **kwargs):
--> 553     return model_forward(*args, **kwargs)

File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\accelerate\utils\operations.py:541, in ConvertOutputsToFp32.__call__(self, *args, **kwargs)
    540 def __call__(self, *args, **kwargs):
--> 541     return convert_to_fp32(self.model_forward(*args, **kwargs))

File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\amp\autocast_mode.py:14, in autocast_decorator.<locals>.decorate_autocast(*args, **kwargs)
     11 @functools.wraps(func)
     12 def decorate_autocast(*args, **kwargs):
     13     with autocast_instance:
---> 14         return func(*args, **kwargs)

File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\denoising_diffusion_pytorch\denoising_diffusion_pytorch.py:788, in GaussianDiffusion.forward(self, img, *args, **kwargs)
    785 t = torch.randint(0, self.num_timesteps, (b,), device=device).long()
    787 img = self.normalize(img)
--> 788 return self.p_losses(img, t, *args, **kwargs)

File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\denoising_diffusion_pytorch\denoising_diffusion_pytorch.py:764, in GaussianDiffusion.p_losses(self, x_start, t, noise, offset_noise_strength)
    760         x_self_cond.detach_()
    762 # predict and take gradient step
--> 764 model_out = self.model(x, t, x_self_cond)
    766 if self.objective == 'pred_noise':
    767     target = noise

File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py:1501, in Module._call_impl(self, *args, **kwargs)
   1496 # If we don't have any hooks, we want to skip the rest of the logic in
   1497 # this function, and just call forward.
   1498 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1499         or _global_backward_pre_hooks or _global_backward_hooks
   1500         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501     return forward_call(*args, **kwargs)
   1502 # Do not call functions when jit is used
   1503 full_backward_hooks, non_full_backward_hooks = [], []

File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\denoising_diffusion_pytorch\denoising_diffusion_pytorch.py:378, in Unet.forward(self, x, time, x_self_cond)
    375     x = attn(x) + x
    376     h.append(x)
--> 378     x = downsample(x)
    380 x = self.mid_block1(x, t)
    381 x = self.mid_attn(x) + x

File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py:1501, in Module._call_impl(self, *args, **kwargs)
   1496 # If we don't have any hooks, we want to skip the rest of the logic in
   1497 # this function, and just call forward.
   1498 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1499         or _global_backward_pre_hooks or _global_backward_hooks
   1500         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501     return forward_call(*args, **kwargs)
   1502 # Do not call functions when jit is used
   1503 full_backward_hooks, non_full_backward_hooks = [], []

File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\container.py:217, in Sequential.forward(self, input)
    215 def forward(self, input):
    216     for module in self:
--> 217         input = module(input)
    218     return input

File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py:1501, in Module._call_impl(self, *args, **kwargs)
   1496 # If we don't have any hooks, we want to skip the rest of the logic in
   1497 # this function, and just call forward.
   1498 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1499         or _global_backward_pre_hooks or _global_backward_hooks
   1500         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501     return forward_call(*args, **kwargs)
   1502 # Do not call functions when jit is used
   1503 full_backward_hooks, non_full_backward_hooks = [], []

File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\einops\layers\torch.py:14, in Rearrange.forward(self, input)
     13 def forward(self, input):
---> 14     return apply_for_scriptable_torch(self._recipe, input, reduction_type='rearrange')

File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\einops\_torch_specific.py:77, in apply_for_scriptable_torch(recipe, tensor, reduction_type)
     74 def apply_for_scriptable_torch(recipe: TransformRecipe, tensor: torch.Tensor, reduction_type: str) -> torch.Tensor:
     75     backend = TorchJitBackend
     76     init_shapes, reduced_axes, axes_reordering, added_axes, final_shapes = \
---> 77         _reconstruct_from_shape_uncached(recipe, backend.shape(tensor))
     78     tensor = backend.reshape(tensor, init_shapes)
     79     if len(reduced_axes) > 0:

File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\einops\einops.py:200, in _reconstruct_from_shape_uncached(self, shape)
    192 # this is enforced when recipe is created
    193 # elif len(unknown_axes) > 1:
    194 #     raise EinopsError(
   (...)
    197 #     )
    198 else:
    199     if isinstance(length, int) and isinstance(known_product, int) and length % known_product != 0:
--> 200         raise EinopsError("Shape mismatch, can't divide axis of length {} in chunks of {}".format(
    201             length, known_product))
    203     unknown_axis = unknown_axes[0]
    204     inferred_length: int = length // known_product

EinopsError: Shape mismatch, can't divide axis of length 25 in chunks of 2

**Comment by lucidrains** [comment]
it probably has to do with the shape of your input

I should add some validation depending on the number of stages in the unet

**Comment by brodymaddox** [comment]
The path passed to the trainer is a folder with a bunch of 100x100 mel spectrograms generated with librosa saved as jpg files. Does any of that raise any issues?

**Comment by lucidrains** [comment]
@brodymaddox try resizing the mel spectrograms to 96x96

**Comment by brodymaddox** [comment]
@lucidrains Thank you very much! That got me past the error. I'll close the issue but I just am wondering why those resolutions are necessary as opposed to anything else? Additionally, is there an upper limit to the resolutions that this library can handle?

**Comment by lucidrains** [comment]
you need to know a bit about the architecture of the neural network doing the denoising. the one in use as default is a unet, and it has N stages of 2x downsampling followed by 2x upsampling. This means the dimensions of your image need to be divisible by 2 ^ N. No restrictions on resolutions as long as you satisfy the above criteria; you may even want more stages

**Comment by brodymaddox** [comment]
I see, thanks for taking the time to explain!

**Comment by lucidrains** [comment]
I'll add some asserts tomorrow with some more explanatory error messages! happy 4th!
