### ISSUE TITLE
wrong FID implementation

### ISSUE THREAD

**Issue by suheey** [lucidrains/denoising-diffusion-pytorch#234]
Hi, Many thanks for your works! But I found different results from your FID code implementation and the original FID score that you [referend](https://github.com/mseitzer/pytorch-fid/tree/master).

And when I add the `self.inception_v3.eval()` on calculate_inception_features function, then I can get the same score with original code. Is it mistake? @lucidrains

**Comment by lucidrains** [comment]
@suheey you are right, it should be in eval! thank you!

**Comment by lucidrains** [comment]
https://github.com/lucidrains/denoising-diffusion-pytorch/commit/596aa34cd52165f7cf95a3751d98b325fccba754
