### ISSUE TITLE
What number should we set as the hidden dimension (hidden_dim) in Attention?

### ISSUE THREAD

**Issue by ArchNew** [lucidrains/denoising-diffusion-pytorch#236]
According to the original implementation of the DDPM, the hidden dimension is the same as the output channel of the ResBlock. But in this version of the implementation, the hidden dimension is fixed to 128. 

I know that multi-head attention is probably better than single-head attention in the original implementation, but I'm not sure the hidden dimension set to a fixed channel number is also better. 

Are there papers discussing this subject? Could anyone kindly recommend some? Thanks a lot!

**Comment by lucidrains** [comment]
where is it fixed to 128? could you point to the line number

**Comment by ArchNew** [comment]
> where is it fixed to 128? could you point to the line number

I'm sorry for not pointing out the specific code. They are as follows:
In both LinearAttention and Attetion definitions, they all have the default values of `dim_head` and `heads` (head number).
https://github.com/lucidrains/denoising-diffusion-pytorch/blob/596aa34cd52165f7cf95a3751d98b325fccba754/denoising_diffusion_pytorch/denoising_diffusion_pytorch.py#L192
https://github.com/lucidrains/denoising-diffusion-pytorch/blob/596aa34cd52165f7cf95a3751d98b325fccba754/denoising_diffusion_pytorch/denoising_diffusion_pytorch.py#L193
The hidden dim in both attention codes are determined by heads and dim_head:
https://github.com/lucidrains/denoising-diffusion-pytorch/blob/596aa34cd52165f7cf95a3751d98b325fccba754/denoising_diffusion_pytorch/denoising_diffusion_pytorch.py#L198C1-L198C1

And the Unet code invokes the attention as follows:
https://github.com/lucidrains/denoising-diffusion-pytorch/blob/596aa34cd52165f7cf95a3751d98b325fccba754/denoising_diffusion_pytorch/denoising_diffusion_pytorch.py#L329C1-L329C1
https://github.com/lucidrains/denoising-diffusion-pytorch/blob/596aa34cd52165f7cf95a3751d98b325fccba754/denoising_diffusion_pytorch/denoising_diffusion_pytorch.py#L334C24-L334C24
Clearly, it uses the defualt `dim_head` and `heads`. Hence, the value of `hidden_dim` is fixed to 128.

**Comment by ArchNew** [comment]
> where is it fixed to 128? could you point to the line number

I'm sorry for not pointing out the specific code. They are as follows:
In both LinearAttention and Attetion definitions, they all have the default values of `dim_head` and `heads` (head number).
https://github.com/lucidrains/denoising-diffusion-pytorch/blob/596aa34cd52165f7cf95a3751d98b325fccba754/denoising_diffusion_pytorch/denoising_diffusion_pytorch.py#L192
https://github.com/lucidrains/denoising-diffusion-pytorch/blob/596aa34cd52165f7cf95a3751d98b325fccba754/denoising_diffusion_pytorch/denoising_diffusion_pytorch.py#L193
The hidden dim in both attention codes are determined by heads and dim_head:
https://github.com/lucidrains/denoising-diffusion-pytorch/blob/596aa34cd52165f7cf95a3751d98b325fccba754/denoising_diffusion_pytorch/denoising_diffusion_pytorch.py#L198C1-L198C1

And the Unet code invokes the attention as follows:
https://github.com/lucidrains/denoising-diffusion-pytorch/blob/596aa34cd52165f7cf95a3751d98b325fccba754/denoising_diffusion_pytorch/denoising_diffusion_pytorch.py#L329C1-L329C1
https://github.com/lucidrains/denoising-diffusion-pytorch/blob/596aa34cd52165f7cf95a3751d98b325fccba754/denoising_diffusion_pytorch/denoising_diffusion_pytorch.py#L334C24-L334C24
Clearly, it uses the defualt `dim_head` and `heads`. Hence, the value of `hidden_dim` is fixed to 128.

**Comment by lucidrains** [comment]
@ArchNew oh no, you are correct, that should be customizable

[done!](https://github.com/lucidrains/denoising-diffusion-pytorch/commit/dcc3da8df75509387d5acfa68b689c9e812b7653)

you can increase that to 64 and 8 for better results (vision transformer literature sometimes push it down to 32 head dimension, but that's the lowest it should go)

**Comment by ArchNew** [comment]
@lucidrains I think you may misunderstand my concern. In the original implementation, the hidden_dim follows the input dimension. And in your implementation, the hidden dimension is set by the users of your code and doesn't change as the input dimension changes. Since you closed this issue, I have to open another one to raise this discussion.
