### ISSUE TITLE
Why use 10000 as the base of the log function?

### ISSUE THREAD

**Issue by bugsuse** [lucidrains/denoising-diffusion-pytorch#246]
https://github.com/lucidrains/denoising-diffusion-pytorch/blob/f264a1eca1ee5a2a28a2859e3dc871d275e9c602/denoising_diffusion_pytorch/denoising_diffusion_pytorch.py#L119

Hi, thanks for your great works.
While I'm looking into your codes, I found the base of the `math.log` function is 10000. May I ask why 10000 is used instead of other numbers?

**Comment by lucidrains** [comment]
@bugsuse that was faithfully transcribed from Ho's [original implementation](https://github.com/hojonathanho/diffusion/blob/1e0dceb3b3495bbe19116a5e1b3596cd0706c543/diffusion_tf/nn.py#L100)

`10000` probably because that is what is used in language modeling

**Comment by bugsuse** [comment]
Got it. Thanks a lot!
