### ISSUE TITLE
Train with Self-Conditoning and Generate without Gives better results

### ISSUE THREAD

**Issue by Leo-T-Zang** [lucidrains/denoising-diffusion-pytorch#247]
Hi Phil and all diffusion coder here,

I am using this diffusion codes for latent text generation. After some testing, I found out if I trained my denoising model with self-conditiong and generate content without it will give me more naturally good results.

So I am curious if it is explainable and if we are supposed to use same setting for training and generation.

Thanks.

**Comment by lucidrains** [comment]
@Leo-T-Zang share a weights and bias report?
