### ISSUE TITLE
How to adapt the U-Net to take in a time vector?

### ISSUE THREAD

**Issue by malbergo** [lucidrains/denoising-diffusion-pytorch#254]
Hi there,

Generically the UNet here take in an [x,t] where x \in [batch_size, channels, L, L] and t is a scalar of shape [batch_size]. I am wondering if its possible to adapt the time scalar to be a vector of shape [batch_size, K] where K is the length of a single time vector. If anyone knows how to do this in a straightforward way, it'd be greatly appreciated!

Best,
Michael

**Comment by lucidrains** [comment]
hey Michael, long time

you can use https://github.com/lucidrains/denoising-diffusion-pytorch/blob/main/denoising_diffusion_pytorch/denoising_diffusion_pytorch_1d.py

**Comment by malbergo** [comment]
Hey Phil :) Hope all is well. Let's catch up sometime.
