### ISSUE TITLE
classifier-free guidance: def interpolate() does not work

### ISSUE THREAD

**Issue by altshiftj** [lucidrains/denoising-diffusion-pytorch#259]
I don't know if I am doing this wrong...

    img1 = torch.load("...")[0].float().to(device).unsqueeze(0)
    img2 = torch.load("...")[1].float().to(device).unsqueeze(0)

    img3 = diffusion.interpolate(img1, img2, t=250, lam=0.5)
    

    ****BZZZZ****
    

img3 = diffusion.interpolate(img1, img2, t=None, lam=0.5)
TypeError: p_sample() missing 1 required positional argument: 'classes'

**Comment by lucidrains** [comment]
@altshiftj ah yea, never wired that up for the CFG example

want to try 1.8.15? i put in a quick fix

**Comment by altshiftj** [comment]
Yeah, it does a thing now
