### ISSUE TITLE
In attend.py, shouldn't the scale be different ?

### ISSUE THREAD

**Issue by MekkCyber** [lucidrains/denoising-diffusion-pytorch#265]
Hello @lucidrains 

I would like to ask you a question about the scale in attend.py forward function. Shouldn't the scale be :(q.shape[-1]*q.shape[1]) ** -0.5 ? because the shape of q in the function is (B, heads, H*W, dim_head). Thank you.

**Comment by lucidrains** [comment]
@MekkCyber `-1` index should refer to `dim_head`?

**Comment by MekkCyber** [comment]
Sorry my bad, I confused it with another scaling factor ! Thank you for replying anyway

**Comment by lucidrains** [comment]
@MekkCyber yup no problem
