### ISSUE TITLE
Question about variable mem_kv in self-attention implementation

### ISSUE THREAD

**Issue by beantr96** [lucidrains/denoising-diffusion-pytorch#267]
Hi, sorry for my trivial question but I am well updated about all variants of self-attention or transformer so I don't know how `mem_kv` is used during the implementation of self-attention. Looks like it is concatenated with k and v in these lines:

```python
mk, mv = map(lambda t: rearrange(t, "h n d -> b h n d", b=b), self.mem_kv)
k, v = map(partial(torch.cat, dim=-2), ((mk, k), (mv, v)))
```
Could you briefly explain or point me to somewhere that I can read up about it? Many thanks

**Comment by lucidrains** [comment]
@beantr96 the technique originated from [a rather old paper](https://arxiv.org/abs/1907.01470)

i'm using it instead of [register tokens](https://arxiv.org/abs/2309.16588)
