### ISSUE TITLE
How should I resume training?

### ISSUE THREAD

**Issue by mikio303** [lucidrains/denoising-diffusion-pytorch#27]
I just conducted training this model, but i noticed that it took enormous hours.
According to READ.ME, check points are published while training, but i don't know how to use it to start training process again. 
Could you tell me how to restart training?

**Comment by kpister** [comment]
There is a `trainer.load` function you can call on the checkpoint files. 
I haven't tried it, but I would guess you can use `trainer.train` again after loading.
