### ISSUE TITLE
Bug in guided diffusion? `cond_fn` on input vs predicted mean

### ISSUE THREAD

**Issue by siddancha** [lucidrains/denoising-diffusion-pytorch#276]
It seems that there might be a bug in the implementation of guided diffusion in `guided_diffusion.py`?

https://github.com/lucidrains/denoising-diffusion-pytorch/blob/5ff2393c72a2a678535ac1c31779684552f18189/denoising_diffusion_pytorch/guided_diffusion.py#L604

If the reverse diffusion step is $p(\mathbf{x}\_{t-1} \mid \mathbf{x}\_t) = \mathcal{N}(\boldsymbol{\mu}, \mathbf{\Sigma})$, then the conditional reverse diffusion step should be:

$$p(\mathbf{x}\_{t-1} \mid \mathbf{x}\_t, y) = \mathcal{N}(\boldsymbol{\mu} + \mathbf{\Sigma}\mathbf{g}, \mathbf{\Sigma}) 
\text{ where } \mathbf{g} = \nabla\_{\mathbf{x\ }\_{t-\ \ 1}}~\log p(y \mid \mathbf{x}\_{t-1})\Big\vert\_{\mathbf{x\ }\_{t-~~1}\ \ =\ \  \boldsymbol{\mu}}$$

That is, the gradient should be evaluated at the *predicted mean* $\boldsymbol{\mu}$. Instead, it is currently evaluated at the input $\mathbf{x}\_t$. This can be fixed by:

```python
    gradient = cond_fn(mean, t, **guidance_kwargs)  # replace "x" with "mean"
```

References:
- [Deep Unsupervised Learning using Nonequilibrium Thermodynamics](https://arxiv.org/abs/1503.03585) (see Eqn. 61)
  <img src="https://github.com/lucidrains/denoising-diffusion-pytorch/assets/6638091/5aecf767-35b4-48d7-bcbd-ca0793244ac0" height=60px/>
- [Diffusion Models Beat GANs on Image Synthesis](https://arxiv.org/abs/2105.05233) (see Eqns. 3-10)
  <img height=22px src=https://github.com/lucidrains/denoising-diffusion-pytorch/assets/6638091/2d60d439-25e9-433a-93d8-55813a48f81b/>,  <img height=22px src=https://github.com/lucidrains/denoising-diffusion-pytorch/assets/6638091/d5f3a038-3fda-4174-9f34-af6c2a59c8b3/>, <img height=28px src=https://github.com/lucidrains/denoising-diffusion-pytorch/assets/6638091/b3e65722-4788-4a7c-aad9-d00f99b9f563/>

**Comment by lucidrains** [comment]
ill let @pengzhangzhi answer this one, as he wrote it

**Comment by pengzhangzhi** [comment]
Hi @siddancha, thanks for rasing the question. The x is the intermediate sample in the reversed process. The code follows the open ai official implementation. Please refer to the link below and let me know if you have further questions.
https://github.com/openai/guided-diffusion/blob/22e0df8183507e13a7813f8d38d51b072ca1e67c/guided_diffusion/gaussian_diffusion.py#L356

**Comment by siddancha** [comment]
Hi @pengzhangzhi, actually, this **IS** a bug in the official OpenAI implementation, which the OpenAI authors acknowledge here: https://github.com/openai/guided-diffusion/issues/51 (see point 1)

FWIW, fixing this bug does give me improvements in my own work.

**Comment by pengzhangzhi** [comment]
Thank you for letting me know!!
