### ISSUE TITLE
a question called "assert len(self.ds) >= 100, 'you should have at least 100 images in your folder. '"

### ISSUE THREAD

**Issue by ZTQAQ** [lucidrains/denoising-diffusion-pytorch#278]
I'm a beginner. And When I tried to train a model. I meet the error reporting. Anyone can help me? Thank you!

import torch
from denoising_diffusion_pytorch import Unet, GaussianDiffusion, Trainer

model = Unet(
    dim = 64,
    dim_mults = (1, 2, 4, 8),
    flash_attn = True
)

diffusion = GaussianDiffusion(
    model,
    image_size = 128,
    timesteps = 1000,           # number of steps
    sampling_timesteps = 250    # number of sampling timesteps (using ddim for faster inference [see citation for ddim paper])
)

trainer = Trainer(
    diffusion,
    'D:\diffusion_model-main\dataset\512x512\train\nolabel',
    train_batch_size = 32,
    train_lr = 8e-5,
    train_num_steps = 700000,         # total training steps
    gradient_accumulate_every = 2,    # gradient accumulation steps
    ema_decay = 0.995,                # exponential moving average decay
    amp = True,                       # turn on mixed precision
    calculate_fid = True              # whether to calculate fid during training
)

trainer.train()

PS E:\code> & d:/ProgramData/Anaconda3/envs/myTorch/python.exe e:/code/pytorch/1.py
Non-A100 GPU detected, using math or mem efficient attention if input tensor is on cuda
Traceback (most recent call last):
  File "e:\code\pytorch\1.py", line 17, in <module>
    trainer = Trainer(
  File "D:\ProgramData\Anaconda3\envs\myTorch\lib\site-packages\denoising_diffusion_pytorch\denoising_diffusion_pytorch.py", line 922, in __init__
    assert len(self.ds) >= 100, 'you should have at least 100 images in your folder. at least 10k images recommended'
AssertionError: you should have at least 100 images in your folder. at least 10k images recommended

![QQ图片20240103181509](https://github.com/lucidrains/denoising-diffusion-pytorch/assets/101617427/2fda12cb-5fee-4827-80a8-b2e6a85c9e81)

I'm sure the folder contains more than ten thousands of photos. So I don't know what is the error.

**Comment by fywwy** [comment]
我也是这个问题，请问你解决了吗
