### ISSUE TITLE
Adapt code to support RePaint

### ISSUE THREAD

**Issue by nilsleh** [lucidrains/denoising-diffusion-pytorch#290]
I found an implementation of [RePaint](https://arxiv.org/pdf/2201.09865.pdf) (Inference Algorithm 1) for image inpainting in the [DALLE2-pytorch repo](https://github.com/lucidrains/DALLE2-pytorch), however, I would like to use a more minimal implementation not dependent on CLIP etc so I am looking how to adapt this code base to support RePaint by taking the implementation from the DALLE2 repo. However, I am not sure if this is correct, specifically I am confused about the order of steps 5-8 from the algorithm pseudocode and the implementation found in DALLE2 repo.

```python
from denoising_diffusion_pytorch import GaussianDiffusion
import torch
from tqdm import tqdm


class RePaintDiffusion(GaussianDiffusion):
    """Adapt Diffusion for Repaint Inference Procedure."""
    
    def q_sample_from_to(self, x_from, from_t, to_t, noise = None):
        shape = x_from.shape
        noise = default(noise, lambda: torch.randn_like(x_from))

        alpha = extract(self.sqrt_alphas_cumprod, from_t, shape)
        sigma = extract(self.sqrt_one_minus_alphas_cumprod, from_t, shape)
        alpha_next = extract(self.sqrt_alphas_cumprod, to_t, shape)
        sigma_next = extract(self.sqrt_one_minus_alphas_cumprod, to_t, shape)

        return x_from * (alpha_next / alpha) + noise * (sigma_next * alpha - sigma * alpha_next) / alpha

    @torch.inference_mode()
    def sample(self, batch_size = 16, return_all_timesteps = False, inpaint_resample_times = 5, inpaint_image=None, inpaint_mask=None):
        image_size, channels = self.image_size, self.channels
        sample_fn = self.p_sample_loop if not self.is_ddim_sampling else self.ddim_sample
        return sample_fn((batch_size, channels, image_size, image_size), return_all_timesteps = return_all_timesteps, inpaint_resample_times = inpaint_resample_times, inpaint_image = inpaint_image, inpaint_mask = inpaint_mask)

    # https://github.com/lucidrains/DALLE2-pytorch/blob/680dfc4d93b70f9ab23c814a22ca18017a738ef6/dalle2_pytorch/dalle2_pytorch.py#L2830
    @torch.inference_mode()
    def p_sample_loop(self, shape, return_all_timesteps: bool = False, inpaint_resample_times : int = 1, inpaint_image=None, inpaint_mask=None):
        """Sample from the diffusion model with optional RePaint inpainting.
        
        Args:
            shape: shape of the output tensor
            return_all_timesteps: whether to return all timesteps
            inpaint_resample_times: number of times to resample the inpainted image
            inpaint_image: the image to be inpainted
            inpaint_mask: the mask to inpaint
        """
        batch_size, device = shape[0], self.device

        # line 1
        img = torch.randn(shape, device = device)
        imgs = [img]

        is_inpaint = exists(inpaint_image) and exists(inpaint_mask)

        if is_inpaint:
            batch_size = inpaint_image.shape[0]

        inpaint_resample_times = inpaint_resample_times if is_inpaint else 1

        x_start = None

        # line 2
        for time in tqdm(reversed(range(0, self.num_timesteps)), desc = 'sampling loop time step', total = self.num_timesteps):
            is_last_timestep = time == 0

            # # line 3
            for u in reversed(range(0, inpaint_resample_times)):
                is_last_resample_step = u == 0
                self_cond = x_start if self.self_condition else None

                times = torch.full((batch_size,), time, device = device, dtype = torch.long)

                if is_inpaint:
                    # line 5
                    noised_inpaint_image = self.q_sample(inpaint_image, t = times)
                    # line 8
                    img = (img * ~inpaint_mask) + (noised_inpaint_image * inpaint_mask)
                # line 7
                img, x_start = self.p_sample(img, time, self_cond)

                # line 9
                if is_inpaint and not (is_last_timestep or is_last_resample_step):
                    # in repaint, you renoise and resample up to 10 times every step
                    img = self.q_sample_from_to(img, times - 1, times)
            
            imgs.append(img)

        if is_inpaint:
            img = (img * ~inpaint_mask) + (inpaint_image * inpaint_mask)

        ret = img if not return_all_timesteps else torch.stack(imgs, dim = 1)

        ret = self.unnormalize(ret)
        return ret
```

**Comment by lucidrains** [comment]
@nilsleh hey Nils

it has been a while, but isn't there an official implementation of repaint?

**Comment by nilsleh** [comment]
Yes, you are correct, there is an [official repo from RePaint](https://github.com/andreas128/RePaint/blob/main/guided_diffusion/gaussian_diffusion.py), however, just like in many other cases it builds on the [OpenAI](https://github.com/openai/guided-diffusion) implementation which does not seem like it is being maintained. In contrast your implementation is actively maintained and improved, for example with the suggested improvements from [Karras et al.](https://arxiv.org/abs/2206.00364) and therefore it seems a much better idea to build "downstream" applications like RePaint based on your actively maintained repo.

**Comment by lucidrains** [comment]
@nilsleh oh i see

ok, i'm getting back into ddpms rest of this month

will take a look at this

is repaint still the best approach after all this time?

**Comment by nilsleh** [comment]
I haven't found a paper that explicitly compares to it. The other paper that seems quiet interesting is a recent ICLR paper called [Diffusion Posterior Sampling Chung et al. 2023](https://openreview.net/forum?id=OnD9zGAGT0k) that is more generally applicable to inverse problems (also has a [repo](https://github.com/DPS2022/diffusion-posterior-sampling) but like repaint based on old OpenAI code). For the task of inpainting it beats [Denoising Difusion Restoration Models](https://arxiv.org/pdf/2201.11793.pdf) (DDRM) which are dated shortly after RePaint. So I think RePaint is still quiet relevant. In my opinion two great downstream models would be: RePaint and Diffusion Posterior Sampling and I would try to extend your codebase to those for the applications I am working on. If you would consider including them in your repo and I can be of any help, I'd be happy to take a stab at it.

**Comment by lucidrains** [comment]
@nilsleh DPS is quite cool! ok, i'll try to allot a stretch of time for these two papers then

**Comment by nilsleh** [comment]
Just for reference when looking into DPS, I came across another paper by same author called [Improving Diffusion Models for Inverse Problems using Manifold Constraints](https://arxiv.org/pdf/2206.00941.pdf) that compares to RePaint and shows some improved results in Table 1.

**Comment by nilsleh** [comment]
@lucidrains saw in another issue that you aren't making any new contributions anymore. Does this also mean you won't have time for these extensions? 😢

**Comment by lucidrains** [comment]
@nilsleh not sure, but there's a good chance I may take a job during mid March. depending on negotiations there could be a chance i will never get to them sorry

**Comment by lucidrains** [comment]
@nilsleh there's a chance i'll never get to them, sorry

**Comment by 903124** [comment]
I've add a pull request to address this
