### ISSUE TITLE
"transcribed from official implementation" -> "Inspired by official implementation" in README.md

### ISSUE THREAD

**Issue by BrunoKM** [lucidrains/denoising-diffusion-pytorch#294]
The `README.md` currently says that the codebase is _transcribed_ from the original [codebase](https://github.com/hojonathanho/diffusion/blob/master/diffusion_tf/models/unet.py):

https://github.com/lucidrains/denoising-diffusion-pytorch/blob/c59ebf49eb8f0e01d773c1ffd7d329079c6a384a/README.md?plain=1#L7

This might be too strong of a claim, as there are too many architectural differences between the two implementations (differences in where attention is placed, different number of residual streams, different number of ResNet blocks in down vs up stages, missing dropout, different activation functions in places, to name a few). It might also be somewhat misleading, as one might expect to use this repository to reproduce the results from the original paper, but the architectures are substantially different (see #114, #192).

I would suggest to rephrase the `README.md` as to better convey that this is a working reimplementation with differences to the original codebase. For example, _"inspired by the official implementation"_, might a good way to convey this. Alternatively, the codebase could be aligned more closely with the original implementation.

**Comment by lucidrains** [comment]
@BrunoKM yes you are correct. it initially was a straight transcription, but now deviates as a lot of research has progressed and got incorporated.

**Comment by BrunoKM** [comment]
Awesome, thanks for addressing this so quickly!

**Comment by lucidrains** [comment]
sorry for the confusion, in case you were doing research on top of the original paper!
