### ISSUE TITLE
Karras UNet 1D + 3D

### ISSUE THREAD

**Issue by MaximilienLC** [lucidrains/denoising-diffusion-pytorch#295]
Would the adjustments to transform the 2D Karras Unet to 1D be the same to the adjustments made to the 2D "standard" UNet to create the 1D one?

Thanks!

**Comment by lucidrains** [comment]
@yup, it is quite simple. i have a 1d MP module here https://github.com/lucidrains/lumiere-pytorch/blob/main/lumiere_pytorch/mp_lumiere.py#L120

would you like me to just knock this out for you tomorrow morning?

**Comment by lucidrains** [comment]
@MaximilienLC what type of data are you working with?

**Comment by MaximilienLC** [comment]
I trust you more than I trust myself so I'll gladly take the offer hhh. Working with audio-like signals that cannot be easily converted to spectrograms. Thanks a lot!

**Comment by lucidrains** [comment]
oh yes audio duh

ok, I'll knock this out tomorrow morning!

**Comment by lucidrains** [comment]
@MaximilienLC gave this more thought while walking doggo, and i think you need 2d still (to mix adjacent frequency information). i'll make it so the unet2d, you can finely control whether to downsample only the height or the width (and customize the conv2d kernel height/width dimensions too). that should generalize the 1d case

**Comment by lucidrains** [comment]
oh sorry I misread, thought you said you were working with spectrogram

**Comment by QuantPrincess** [comment]
While we are on the topic... If I wanted to adjust the original Unet to support a 3d input would the adjustments roughly be similar in terms of changing the conv to 3d + some other minor adjustments?

**Comment by lucidrains** [comment]
@QuantPrincess yup, similar complexity. i'm planning on just copy pasting my own code and making a few changes lol

**Comment by QuantPrincess** [comment]
Amazing! Thank you.

**Comment by lucidrains** [comment]
@QuantPrincess what are you using it for? the latest video unets are all pretrained with conv2d  with conv1d slipped in for time dimension (unless if Sora changed all that, haven't read the technical paper yet)

**Comment by lucidrains** [comment]
@MaximilienLC knocked it out just now - let me know if [this](https://github.com/lucidrains/denoising-diffusion-pytorch/commit/e39893bd4b267447df7936608eafaf82286d45cb#diff-06984033216bad48f109d906e39f754f9ab938bea57c6382ad0336f235e0712bR714) runs for you

**Comment by lucidrains** [comment]
@QuantPrincess i can get out a 3d version too, if you aren't doing video stuff. if you are, i'd recommend [this](https://github.com/lucidrains/lumiere-pytorch/blob/main/lumiere_pytorch/mp_lumiere.py)

**Comment by QuantPrincess** [comment]
Thanks so much, really appreciate the recommendation.

**Comment by lucidrains** [comment]
@QuantPrincess ohh got it, you working with CT / MRI segmentation? yea i can add 3d for you then

**Comment by QuantPrincess** [comment]
Haha yes CTs! Thanks so much for your help. Your code base is really a pleasure to work with.

**Comment by lucidrains** [comment]
@QuantPrincess awesome! yea i'll get that done

brings back memories of grad school when i tried to segment kidneys in CT scans with gofai algorithms (our team used watershed segmentation). oh how far things have come

**Comment by lucidrains** [comment]
@QuantPrincess i remember going to office hours and our CV professor had a daunting number of books filled with different CV algorithms. now all that is obsolete by convs and attention.

**Comment by MaximilienLC** [comment]
> @MaximilienLC knocked it out just now - let me know if [this](https://github.com/lucidrains/denoising-diffusion-pytorch/commit/e39893bd4b267447df7936608eafaf82286d45cb#diff-06984033216bad48f109d906e39f754f9ab938bea57c6382ad0336f235e0712bR714) runs for you

Thanks @lucidrains, will do in the coming days and report back!

btw, you might have missed my latest question

> I'm planning to eventually transition to conditional modeling, following the concatenation scheme proposed in Palette & Image Super-Resolution via Iterative Refinement (add extra channels with your conditional info). I'm not super familiar with all the changes that need to be made yet but will eventually (is [the concatenation all you need](https://github.com/lucidrains/denoising-diffusion-pytorch/issues/98#issuecomment-1684920639)?) Do you think that your lib is flexible enough for me to add this conditioning feature (btw would be happy to propose a PR if I succeed)?

**Comment by lucidrains** [comment]
@MaximilienLC unfortunately there is the possibility my open source journey comes to an end soon and i can't get around to that. PR is welcome!

**Comment by QuantPrincess** [comment]
Thank you for this! I will check out today and report back. Really appreciate your help. :)

**Comment by lucidrains** [comment]
@QuantPrincess let me get those in there this weekend

**Comment by QuantPrincess** [comment]
I definitely will! I will also try to make my own adjustments and send to you if it works. Quick (probably stupid) question: if I already have my data in one big numpy array consisting of 850 3d images (instead of individual files) I just need to alter the trainer class to take in that as the dataset as you did in denoising_diffusion_pytorch_1d.py. Is that correct?

**Comment by lucidrains** [comment]
@QuantPrincess let me know if [this](https://github.com/lucidrains/denoising-diffusion-pytorch/blob/main/denoising_diffusion_pytorch/karras_unet_3d.py#L763-L780) is intuitive

with `downsample_types`, you can control at each stage whether to downsample `image` (spatial) or `frame` (slices) or `all` (both). you can also control how many MP resnet blocks are at each stage by passing in a tuple of integer into `num_blocks_per_stage`

**Comment by lucidrains** [comment]
@QuantPrincess i can get to the factorized attention mid next week and finish off this issue

**Comment by lucidrains** [comment]
@QuantPrincess are you using some of the newer techniques (adapting ddpm for segmentation), or you were just interested in the unet?

**Comment by QuantPrincess** [comment]
Thank you! I will look at tonight and get back to you. I really can't express enough how awesome your code base is to work with!

**Comment by Parskatt** [comment]
I think there might be some implementation mistake in the 3DUnet, I'm getting exploding activations. I'll see if I can make a simple repro.

**Comment by Parskatt** [comment]
@lucidrains see https://github.com/lucidrains/denoising-diffusion-pytorch/pull/296

**Comment by lucidrains** [comment]
@QuantPrincess ok, with [this flag](https://github.com/lucidrains/denoising-diffusion-pytorch/commit/5f8aa9feacb651c77ecd5a13dfd769bb7dd5c76d#diff-0829e810809760281dbba1e39eda0f9754da7c69298fab54fa1f250a31566440R844), you can do attention across space and time separately (axial attention)

this is my last open source contribution until further notice, good luck!

**Comment by QuantPrincess** [comment]
Thanks so much @lucidrains ! Cant wait to test out your work on the axial attention. Best of luck on your next endeavors!
