### ISSUE TITLE
Bug in RePaint implementation: p_sample input args and resample loop

### ISSUE THREAD

**Issue by AlejandroSantorum** [lucidrains/denoising-diffusion-pytorch#319]
Dear @lucidrains,

Thank you for your outstanding work! I really appreciate all the effort put in this project.

I have been working with the `inpaint.py` implementation, which has been recently added to this repository, and I have found a couple of issues with the current implementation:
1) When calling the method `p_sample` [in the resample loop the input argument names are not used](https://github.com/lucidrains/denoising-diffusion-pytorch/blob/main/denoising_diffusion_pytorch/repaint.py#L708), and then the input parameters are incorrectly placed, causing the variable `gt` be fed into `x_self_cond` and `mask` into `gt`.
2) When comparing the code of the method `p_sample_loop` with the algorithm 1 of the original paper (https://arxiv.org/pdf/2201.09865), it's clear than the [resample loop](https://github.com/lucidrains/denoising-diffusion-pytorch/blob/main/denoising_diffusion_pytorch/repaint.py#L702) should be [inside the normal sampling loop and not after it at the same level](https://github.com/lucidrains/denoising-diffusion-pytorch/blob/main/denoising_diffusion_pytorch/repaint.py#L694).

I think @nilsleh has already realized some of these issues and he has kindly fixed some of them. I am creating a new PR to address some of the remaining imperfections.

Again, thank you for your work!

**Comment by lucidrains** [comment]
no problem! thank you for contributing!
