### ISSUE TITLE
Enable flash attention for compute capability >= 8.0, not == 8.0

### ISSUE THREAD

**Issue by gau-nernst** [lucidrains/denoising-diffusion-pytorch#328]
https://github.com/lucidrains/denoising-diffusion-pytorch/blob/3bee3779e9de203e5e6115f6a952ec3845cad000/denoising_diffusion_pytorch/attend.py#L63-L68

This should be changed to >= 8.0 instead of == 8.0 so that other GPUs like 4090, L4, H100... will use flash attention too.

```python
if (device_properties.major, device_properties.minor) >= (8, 0):
    ...
```

**Comment by lucidrains** [comment]
@gau-nernst done!

**Comment by gau-nernst** [comment]
Your updated logic won't work with compute capability 8.6 (e.g. A10, A2000) and 8.9 (e.g. 4090, L40) though :(
That's why I was suggesting using `(device_properties.major, device_properties.minor) >= (8, 0)`, which will handle 8.x, 9.x (Hopper), and above, correctly.

**Comment by lucidrains** [comment]
@gau-nernst oops, how about now?

**Comment by gau-nernst** [comment]
I think it should work! Will confirm it later on my machine. Thank you!

**Comment by gau-nernst** [comment]
I can confirm that it works with the latest fix! Thank you again!

**Comment by lucidrains** [comment]
@gau-nernst nice! happy training
