### ISSUE TITLE
KarrasUnet1D fails in the decoder for some sequence length/num. channel combinations

### ISSUE THREAD

**Issue by andleb** [lucidrains/denoising-diffusion-pytorch#336]
When selecting short sequence lengths, such as 2, 4, 8 together with 1 channel, `KarrasUnet1D` fails when concatenating the skip connections in the decoder.

Example:
```python
batch_size = 100
seq_len = 8
nchannel = 1

seq = torch.randn(batch_size,  seq_len).unsqueeze(1)

unet = KarrasUnet1D(
    seq_len = seq_len,
    channels = nchannel,
    #NOTE:  Example dimensions
    dim=192,
    dim_max=768,
)

diffusion = GaussianDiffusion1D(unet, seq_length=seq_len, timesteps=100)
loss = diffusion(seq)
```

produces:
```
/karras_unet_1d.py:664, in KarrasUnet1D.forward(self, x, time, self_cond, class_labels)
    662     if decoder.needs_skip:
    663         skip = skips.pop()
--> 664         x = self.skip_mp_cat(x, skip)
    666     x = decoder(x, emb=emb)
    668 # output block

...


/karras_unet_1d.py:113, in MPCat.forward(self, a, b)
    110 a = a * (1. - t) / sqrt(Na)
    111 b = b * t / sqrt(Nb)
--> 113 return C * torch.cat((a, b), dim=dim)

RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 1 but got size 2 for tensor number 1 in the list.
```
(apologies if the line numbers are a bit off, I'm up to date, but have annotated the code a bit with comments)

This is reproducible across different choices of `dim` and `dim_max`, even when reducing these (given the sequence length).

I'm not super familiar with Karras' UNet architecture, so if there's a good heuristic for adjusting the other parameters to avoid this, such as `att_res`, I'd really appreciate some feedback.

**Comment by lucidrains** [comment]
@andleb hmm your example runs for me

could you paste your entire script?

**Comment by andleb** [comment]
@lucidrains I've just cloned a fresh copy of yours and putting this 
```if __name__ == '__main__':

    from karras_unet_1d import KarrasUnet1D

    batch_size = 100
    seq_len = 8
    nchannel = 1

    seq = torch.randn(batch_size,  seq_len).unsqueeze(1)

    unet = KarrasUnet1D(
    seq_len = seq_len,
    channels = nchannel,
    # Example settings
    dim=192,
    dim_max=768,
    )

    diffusion = GaussianDiffusion1D(unet, seq_length=seq_len, timesteps=100)
    loss = diffusion(seq)
```
at the bottom of `denoising_diffusion_pytorch/denoising_diffusion_pytorch_1d.py` 
works for the fresh copy, while it fails for mine.

What happened is that I ran PyCharm's code formatter on my copy (confirmed with git history that there are no other changes) and it broke something. 
I'm sorry; thank you for the quick response, your work is awesome!
