### ISSUE TITLE
How to do inpainting?

### ISSUE THREAD

**Issue by moghadas76** [lucidrains/denoising-diffusion-pytorch#339]

**Comment by lucidrains** [comment]
@moghadas76 try [repaint](https://github.com/lucidrains/denoising-diffusion-pytorch/blob/main/denoising_diffusion_pytorch/repaint.py)

**Comment by wadie999** [comment]
@lucidrains is there any documentation on the different classes in repaint.py and paint.py ? it wasn't specified on hw to use these classes to make image restauration
