### ISSUE TITLE
Clarification on T in DDPM paper and train_num_steps in the code

### ISSUE THREAD

**Issue by littlewhite132** [lucidrains/denoising-diffusion-pytorch#347]
Hi,

In the DDPM paper, T is set to 1000, but in this code, the default value for train_num_steps is 700000. I wanted to clarify if T in the DDPM paper corresponds to train_num_steps in this code, or if they represent different concepts. Could you please explain the relationship between these two values?

Thank you!

**Comment by 2829610594** [comment]
Hi，

I'm using DDPM for the first time and I also have this question. May I ask if you have solved it? And what's your understanding of it?

Thank you!
