### ISSUE TITLE
model image size conflict in Trainer unless specified as an argument

### ISSUE THREAD

**Issue by pumplerod** [lucidrains/denoising-diffusion-pytorch#40]
i denoising_diffusion_pytorch.py in the Trainer Class init there is an option for 'image_size' which has a default value of 128, and these arguments are not documented anywhere I could locate.

The issue then comes later inside the init method where you set: 
    self.image_size = diffusion_model.image_size

however, when the Dataset instance is declared is is initialized with:
    self.ds = Dataset( folder, image_size, augment_horizontal_filip = augment_horizontal_filp)

So, if one has originally created a diffusion_model with an image size of 64, but does not know to set the argument on the Trainer, then a default image size of 128 will be used and cause a conflict.

I believe it can be fixed by simply declaring the Dataset with self.image_size, instead of image_size.

**Comment by lucidrains** [comment]
@pumplerod https://github.com/lucidrains/denoising-diffusion-pytorch/commit/1586d1a8a07fb7308c596d914c712215255f2b7a let me know if that works!

**Comment by pumplerod** [comment]
Thank you. I'm traveling now so it will be a while before I can test it out. But I'm looking forward to it. 

-t
