### ISSUE TITLE
How to reduce time steps' computation time working on Google Colab

### ISSUE THREAD

**Issue by vinz97** [lucidrains/denoising-diffusion-pytorch#43]
Hi,
first of all thanks for this repository and for your work. I'm a student that is working with this code for a project's university. My aim is to replicate the results written in this [paper](https://arxiv.org/pdf/2006.11239.pdfl) using the same parameters.
I tried to run the code with Colab, but the computation time for each step is really huge (e.g. 1000 steps in 4 hours); how can i reduce the computation time for each step? Is there some optimization that i can do to speed-up the training?
Any suggestions (also from other users, not only the creator of this repo) would be appreciated. Thank you!

PS i'm using the CIFAR10 as dataset

**Comment by johnowhitaker** [comment]
The paper does 800k steps with a batch size of 128 on a TPU v3-8 (similar to 8 V100 GPUs)  for CIFAR10, which takes them >10 hours. 
On a single GPU like those in Google Colab it'd probably take days and days to train as much as they do. BUT the training will have diminishing returns - you might be able to get away with only a few hours of training as long as you're OK with lower sample quality.
Here's a quick test I've just tried that does ~2000 steps/hour with a batch size of 300 (so ~600k samples/hour) on a P100 in Colab: https://colab.research.google.com/drive/1dlk4n199sEdYBWQDph_s5F_lJ_EDT-ZZ?usp=sharing
You may want to use a lower batch size depending on what GPU you get. I tried to roughly match the settings of the cifar10 model in the DDPM paper you link but it's not an exact replication.

**Comment by vinz97** [comment]
@johnowhitaker thank you a lot! I can do at least 5000 steps/hour with a resized batch size.
Also, i think you're the creator of the[ AIAIART7 ](https://github.com/johnowhitaker/aiaiart/blob/master/AIAIART_7.ipynb). I learned all the most important concepts about the diffusion models thanks to your Colab file, so thanks twice!
One last question: the train method used in this repo concatenates 36 images on a single image during the "save" method; is it right to compute the metrics like FID, Inception Score or NLL using these images? or is better to save the image one by one (remember they're 32x32) instead of concatenating it in larger image?
If the answer for the last question is yes, i think there's the necessity to modify the code of this repo in that training part
