### ISSUE TITLE
self.update_ema_every set but never used

### ISSUE THREAD

**Issue by johnowhitaker** [lucidrains/denoising-diffusion-pytorch#44]
In denoising_diffusion_pytorch/denoising_diffusion_pytorch.py
class `Trainer` takes an argument `update_ema_every = 10,` and sets `self.update_ema_every = update_ema_every` but then this is not used. `self.ema.update()` is called every step. 

Suggested fix:
```
if self.step != 0 and self.step % self.update_ema_every == 0:
    self.ema.update()
```

EDIT: I see ema_pytorch can take in `update_every`, so a better fix is to switch `self.ema = EMA(diffusion_model, beta = ema_decay)` with `self.ema = EMA(diffusion_model, beta = ema_decay, update_every=self.update_ema_every)`.

Not sure if this is just a temporary issue due to the EMA bits being partly moved to ema_pytorch but figured I should point it out in case it got missed :)

**Comment by lucidrains** [comment]
@johnowhitaker oh yes Jonathan, you are correct https://github.com/lucidrains/denoising-diffusion-pytorch/commit/75ea49a7eff6e5b5a922f0fa2a9a2b06eab137be :pray:
