### ISSUE TITLE
Question about p2_loss_weight

### ISSUE THREAD

**Issue by Kitsunetic** [lucidrains/denoising-diffusion-pytorch#50]
Thank you such a great work.

I have question about `p2_loss_weight` in [here](https://github.com/lucidrains/denoising-diffusion-pytorch/blob/9939a481390d9223d607b7a09fd01a292494702f/denoising_diffusion_pytorch/denoising_diffusion_pytorch.py#L432).
```py
# calculate p2 reweighting
register_buffer("p2_loss_weight", (p2_loss_weight_k + alphas_cumprod / (1 - alphas_cumprod)) ** -p2_loss_weight_gamma)
```

It is saying it followed the original paper [paper](https://openaccess.thecvf.com/content/CVPR2022/papers/Choi_Perception_Prioritized_Training_of_Diffusion_Models_CVPR_2022_paper.pdf).
Eq. 5 of the paper is: $\mathcal E_{x_{0,\epsilon}}\left[\frac{\beta_t}{(1-\beta_t)(1-\bar{\alpha}_t)}\right]$.
But your implementation is: $\left(\frac{\bar{\alpha}}{1-\bar{\alpha}}\right)^{-\gamma}$.

I don't understand how you induced this formula of the implementation.

Thank you.

**Comment by zdhNarsil** [comment]
I have the same question.

**Comment by ynwag09** [comment]
it is p2 loss weight from https://arxiv.org/abs/2204.00227 

check out (8) equation in paper
