### ISSUE TITLE
[QUESTION] Higher memory requirements in recent updates

### ISSUE THREAD

**Issue by xenova** [lucidrains/denoising-diffusion-pytorch#56]
Hi there.

I just had a question about some of the recent (<1 month) changes that have caused an increase in memory requirements.

I used to work on an older version of the repo (I think before the 25th of May), and I was able to train the network on 512x512 2-channel images (with the default UNet parameters as stated in the README).

However, after updating the repo, I am experiencing out of memory errors. If I am not mistaken, this was the first change that caused a problem: https://github.com/lucidrains/denoising-diffusion-pytorch/commit/e5a18bb25ca73a068647f4652933b07f3ef2ed74, but I would have to do some extra checks to be certain. It doesn't sound impossible considering the linear layer of the resnet block has twice as many outputs.

The main reason I bring this up is because I must be able to train on a RTX2080 with 8GB of VRAM (with the above-mentioned input dimensions).

So, a few questions:
- Are there any optimisations I can try to use less memory? I have tried using fp16, but this doesn't work.
- What changes would you recommend I make to slightly decrease memory usage, but not have a massive impact on performance? For example, I was able to get the memory to be under 8GB by using a UNet with an initial dimension of 54, but I would rather try other things before reducing this value.
- Is it wise to "revert" some of the recent changes (e.g., those linked to above) to reduce memory usage?

Thanks!

**Comment by lucidrains** [comment]
@xenova time to upgrade your GPU to 16GB, especially given the falling prices because of the crypto crash

you won't get very far with 8GB in machine learning research these days

**Comment by lucidrains** [comment]
@xenova speaking of which, time for me to upgrade to 24GB :thinking:

**Comment by lucidrains** [comment]
i'll eventually build out https://arxiv.org/abs/1906.06148 in this repository too, just to understand if it is good for DDPM use

**Comment by xenova** [comment]
> @xenova time to upgrade your GPU to 16GB, especially given the falling prices because of the crypto crash
> 
> 
> 
> you won't get very far with 8GB in machine learning research these days
> 
> 
> 
> another option is to buy a [colab pro](https://colab.research.google.com/signup) and you'll have 16GB immediately in the cloud

Yeah I probably should haha. My trusty 2080 has served me well for the past few years, but I clearly need more powerful hardware. 

I've tried to use google colab pro, but my country isn't supported 😢
