### ISSUE TITLE
incorrect process on dataloader

### ISSUE THREAD

**Issue by bibona** [lucidrains/denoising-diffusion-pytorch#69]
In Trainer code, `self.dl` is an iterator returned by function `cycle`, which can't be correctly processed by `Accelerator.prepare` and will return the iterator itself. The result is that the batch yielded by dataloader will not be splited over multi gpus.

Putting `self.dl = cycle(dl)` after `self.accelerator.prepare` can solve this  problem.

**Comment by lucidrains** [comment]
@bibona thanks! does https://github.com/lucidrains/denoising-diffusion-pytorch/commit/6b504c4ae9bffa6c36cbfb6a23ee5aba11c4e508 resolve the issue for you?

**Comment by bibona** [comment]
@lucidrains it works! thanks!
