### ISSUE TITLE
Generalise to 3D input

### ISSUE THREAD

**Issue by danieltudosiu** [lucidrains/denoising-diffusion-pytorch#71]
Hi lucidrains,

Again, thanks a lot for the amazing work you are doing with all your repos.

Could you please try and generalise this codebase to 3D inputs?

Best regards,

Dan

**Comment by FirasGit** [comment]
Hi @danieltudosiu, if you're still looking for a 3D implementation: We have published the code to our paper where we generate three-dimensional medical images at https://github.com/FirasGit/medicaldiffusion. We based the code largely on the amazing repositories built by lucidrains.
