### ISSUE TITLE
About time embedding implementation

### ISSUE THREAD

**Issue by three0-s** [lucidrains/denoising-diffusion-pytorch#77]
https://github.com/lucidrains/denoising-diffusion-pytorch/blob/beb2f2d8dd9b4f2bd5be4719f37082fe061ee450/denoising_diffusion_pytorch/denoising_diffusion_pytorch.py#L183

Hi, thanks for your great works.
While I'm looking into your codes, I found that the dimensionality of time embedding gets twice and then chunked by half during the training process. I have no idea about this implementation. Is it just a mistake or intended?

**Comment by lucidrains** [comment]
@three0-s Hi Yewon

It is intended! It is adopted from the latest and greatest text to image models. They use a [FiLM](https://distill.pub/2018/feature-wise-transformations/) like conditioning with both a scale and shift (instead of just shift as in the original ddpm paper)

**Comment by lucidrains** [comment]
you can just think of it as stronger type of conditioning

**Comment by three0-s** [comment]
@lucidrains thank you Phil 😁
I will take a look into that reference.
