### ISSUE TITLE
DDIM sampling mistake

### ISSUE THREAD

**Issue by lukovnikov** [lucidrains/denoising-diffusion-pytorch#81]
I think there is a mistake in the code for DDIM sampling, in particular for the generation of time steps and selection of alpha_cumprod's. Currently, the `time_pairs` list ends with `(0, 0)`, which doesn't make sense to me in my current understanding of the matter. I also don't understand why `self.alphas_cumprod_prev` is being used instead of `self.alphas_cumprod`, which is what it seems we need according to the equations.

I fixed this and can make a pull request but I before that I wanted to ask how we can verify that my implementation is correct.

I looked at sampling trajectories generated for a simple 1D task with the old code and my fixed code, and my code appears to give smoother trajectories whereas the old code had trajectories with unnecessary bends.

Can someone check if the current DDIM code makes sense?

**Comment by lucidrains** [comment]
@lukovnikov Hi Denis

I do believe you are correct, once I checked it against https://github.com/openai/glide-text2im/blob/18bf97a07446874693263715af6a73a09cbe81e2/glide_text2im/gaussian_diffusion.py#L484

As for the `(0, 0)` in the time pairs list, how many timesteps and sampling timesteps was set on your gaussian diffusion class?

I put in an extra precautionary filter, but it is a weird edge case

**Comment by lukovnikov** [comment]
Thanks for checking it so quickly!
I was using 100 timesteps and left sampling timesteps to default but it also occurs whith 1000 steps. I think with the current version, we still miss the last step corresponding to timestep 0 in the code (which would be t=1 in the equations and still has supertiny but nonzero noise and x_T added to it), and somehow it makes it skip the first "jump" if you use fewer steps to speed up DDIM.

I made a pull request (#83) with some fixes that I think give the correct time steps.
