### ISSUE TITLE
How many pictures are needed?

### ISSUE THREAD

**Issue by mertyyanik** [lucidrains/denoising-diffusion-pytorch#87]
How many pictures are we need for proper training? Can we use your stylegan2 augmentation for this kind of method?

**Comment by lucidrains** [comment]
@mertyyanik DDPMs are actually already much better than GANs, probably on the order of 1000 images and you should be fine, but that number can probably be dropped to the hundreds using Tero Karras' new finding in the elucidated DDPM paper

i will add his augmentation techniques when i find the time

**Comment by mertyyanik** [comment]
Thank you so much @lucidrains
