### ISSUE TITLE
Avoid crashing with grey-scale images

### ISSUE THREAD

**Issue by ArashAkbarinia** [lucidrains/denoising-diffusion-pytorch#89]
Thanks a lot for the amazing code :).

If you please change line 722 of the "denoising_diffusion_pytorch.py" to "img = Image.open(path)**.convert('RGB')**", the code wouldn't crash if there are grey-scale images in the image folder.

**Comment by lucidrains** [comment]
@ArashAkbarinia Hi Arash

You can set https://github.com/lucidrains/denoising-diffusion-pytorch/blob/main/denoising_diffusion_pytorch/denoising_diffusion_pytorch.py#L700 to `"RGB"`

**Comment by ArashAkbarinia** [comment]
Thanks a lot @lucidrains , I hadn't paid attention to that parameter.
I close the case :).
