### ISSUE TITLE
Bug related to convert_image_to?

### ISSUE THREAD

**Issue by tqch** [lucidrains/denoising-diffusion-pytorch#91]
Line 707 of `denoising_diffusion_pytorch.py`
```
maybe_convert_fn = partial(convert_image_to, convert_image_to) if exists(convert_image_to) else nn.Identity()
```
How can convert_image_to be a callable and a valid positional argument of itself at the same time? Setting `convert_image_to` to `"RGB"` while the data folder contains RGBA images will produce an error.

**Comment by lucidrains** [comment]
@tqch whoops, that's embarrassing! thanks! https://github.com/lucidrains/denoising-diffusion-pytorch/commit/6e8a0f208265a6e58a3e3d500fdc9f41a6060080
