### ISSUE TITLE
ddim_sampling_eta: What is it for?

### ISSUE THREAD

**Issue by RyannDaGreat** [lucidrains/denoising-diffusion-pytorch#93]
Hi, what's ddim_sampling_eta used for?

**Comment by martinriven** [comment]
this is a parameter, you can see it in the DDIM paper(Denoising Diffusion Implicit Models). In a word, it is used to determine the amount of randomness. eta=0 means it is a deterministic process, random noise is of no use. eta = 1 means the original ddpm process.

**Comment by RyannDaGreat** [comment]
Thank you - this helped!
